"""Every nation: ISO code, centroid, capital, region, Google News edition language, aliases.

Tuple layout: (code, name, region, lat, lon, capital, cap_lat, cap_lon, gnews_lang, aliases)
`aliases` is a '|' separated list of demonyms / alternative names used by the gazetteer.
"""

COUNTRIES = [
 # ---- Europe ----
 ("AL","Albania","Europe",41.15,20.17,"Tirana",41.33,19.82,"sq","Albanian"),
 ("AD","Andorra","Europe",42.55,1.60,"Andorra la Vella",42.51,1.52,"ca","Andorran"),
 ("AT","Austria","Europe",47.52,14.55,"Vienna",48.21,16.37,"de","Austrian|Österreich|Wien"),
 ("BY","Belarus","Europe",53.71,27.95,"Minsk",53.90,27.57,"ru","Belarusian|Belarussian|Lukashenko"),
 ("BE","Belgium","Europe",50.50,4.47,"Brussels",50.85,4.35,"fr","Belgian|Bruxelles|Belgique|Belgien"),
 ("BA","Bosnia and Herzegovina","Europe",43.92,17.68,"Sarajevo",43.86,18.41,"bs","Bosnia|Bosnian|Herzegovina|Republika Srpska"),
 ("BG","Bulgaria","Europe",42.73,25.49,"Sofia",42.70,23.32,"bg","Bulgarian"),
 ("HR","Croatia","Europe",45.10,15.20,"Zagreb",45.81,15.98,"hr","Croatian"),
 ("CY","Cyprus","Europe",35.13,33.43,"Nicosia",35.17,33.36,"en","Cypriot"),
 ("CZ","Czech Republic","Europe",49.82,15.47,"Prague",50.08,14.44,"cs","Czechia|Czech|Praha"),
 ("DK","Denmark","Europe",56.26,9.50,"Copenhagen",55.68,12.57,"da","Danish|Danes|Danmark|København|Greenland|Faroe"),
 ("EE","Estonia","Europe",58.60,25.01,"Tallinn",59.44,24.75,"et","Estonian"),
 ("FI","Finland","Europe",61.92,25.75,"Helsinki",60.17,24.94,"fi","Finnish|Finns|Suomi"),
 ("FR","France","Europe",46.23,2.21,"Paris",48.86,2.35,"fr","French|Macron|Élysée|Elysee|Frankreich|Francia"),
 ("DE","Germany","Europe",51.17,10.45,"Berlin",52.52,13.40,"de","German|Germans|Deutschland|Bundestag|Allemagne|Alemania"),
 ("GR","Greece","Europe",39.07,21.82,"Athens",37.98,23.73,"el","Greek|Greeks|Hellenic|Athènes"),
 ("HU","Hungary","Europe",47.16,19.50,"Budapest",47.50,19.04,"hu","Hungarian|Orbán|Orban|Magyar"),
 ("IS","Iceland","Europe",64.96,-19.02,"Reykjavik",64.15,-21.94,"is","Icelandic|Reykjavík"),
 ("IE","Ireland","Europe",53.41,-8.24,"Dublin",53.35,-6.26,"en","Irish|Éire|Taoiseach"),
 ("IT","Italy","Europe",41.87,12.57,"Rome",41.90,12.50,"it","Italian|Italians|Italia|Roma|Meloni|Italie|Italien"),
 ("XK","Kosovo","Europe",42.60,20.90,"Pristina",42.66,21.17,"sq","Kosovar|Prishtina"),
 ("LV","Latvia","Europe",56.88,24.60,"Riga",56.95,24.11,"lv","Latvian"),
 ("LI","Liechtenstein","Europe",47.17,9.56,"Vaduz",47.14,9.52,"de",""),
 ("LT","Lithuania","Europe",55.17,23.88,"Vilnius",54.69,25.28,"lt","Lithuanian"),
 ("LU","Luxembourg","Europe",49.82,6.13,"Luxembourg",49.61,6.13,"fr","Luxembourgish"),
 ("MT","Malta","Europe",35.94,14.38,"Valletta",35.90,14.51,"en","Maltese"),
 ("MD","Moldova","Europe",47.41,28.37,"Chisinau",47.01,28.86,"ro","Moldovan|Chișinău|Transnistria"),
 ("MC","Monaco","Europe",43.73,7.42,"Monaco",43.73,7.42,"fr","Monégasque"),
 ("ME","Montenegro","Europe",42.71,19.37,"Podgorica",42.44,19.26,"sr","Montenegrin"),
 ("NL","Netherlands","Europe",52.13,5.29,"Amsterdam",52.37,4.90,"nl","Dutch|Holland|The Hague|Nederland|Pays-Bas|Países Bajos|Niederlande"),
 ("MK","North Macedonia","Europe",41.61,21.75,"Skopje",42.00,21.43,"mk","Macedonian|Macedonia"),
 ("NO","Norway","Europe",60.47,8.47,"Oslo",59.91,10.75,"no","Norwegian|Norwegians|Norge|Svalbard"),
 ("PL","Poland","Europe",51.92,19.15,"Warsaw",52.23,21.01,"pl","Polish|Poles|Polska|Warszawa|Pologne|Polen|Polonia"),
 ("PT","Portugal","Europe",39.40,-8.22,"Lisbon",38.72,-9.14,"pt-PT","Portuguese|Lisboa"),
 ("RO","Romania","Europe",45.94,24.97,"Bucharest",44.43,26.10,"ro","Romanian|București|Bucuresti"),
 ("RU","Russia","Europe",61.52,105.32,"Moscow",55.76,37.62,"ru","Russian|Russians|Kremlin|Putin|Moskva|Russie|Rusia|Russland|Rússia|Россия|Москва|Кремль|Путин"),
 ("SM","San Marino","Europe",43.94,12.46,"San Marino",43.94,12.45,"it","Sammarinese"),
 ("RS","Serbia","Europe",44.02,21.01,"Belgrade",44.79,20.47,"sr","Serbian|Serbs|Beograd|Vučić|Vucic"),
 ("SK","Slovakia","Europe",48.67,19.70,"Bratislava",48.15,17.11,"sk","Slovak|Slovakian"),
 ("SI","Slovenia","Europe",46.15,14.99,"Ljubljana",46.06,14.51,"sl","Slovenian|Slovene"),
 ("ES","Spain","Europe",40.46,-3.75,"Madrid",40.42,-3.70,"es","Spanish|Spaniards|España|Catalonia|Catalan|Barcelona|Espagne|Spanien|Espanha"),
 ("SE","Sweden","Europe",60.13,18.64,"Stockholm",59.33,18.07,"sv","Swedish|Swedes|Sverige|Suède|Schweden|Suecia"),
 ("CH","Switzerland","Europe",46.82,8.23,"Bern",46.95,7.45,"de","Swiss|Geneva|Zurich|Zürich|Schweiz|Suisse|Suiza|Davos"),
 ("UA","Ukraine","Europe",48.38,31.17,"Kyiv",50.45,30.52,"uk","Ukrainian|Ukrainians|Kiev|Zelensky|Zelenskyy|Zelenskiy|Donbas|Donetsk|Luhansk|Kharkiv|Odesa|Odessa|Crimea|Zaporizhzhia|Kherson|Україна|Київ|Ucrania|Ukraina"),
 ("GB","United Kingdom","Europe",55.38,-3.44,"London",51.51,-0.13,"en","UK|U.K.|Britain|British|Britons|England|English|Scotland|Scottish|Wales|Welsh|Northern Ireland|Westminster|Downing Street|Starmer|Royaume-Uni|Reino Unido|Großbritannien|Großbritannien|Grande-Bretagne"),
 ("VA","Vatican City","Europe",41.90,12.45,"Vatican City",41.90,12.45,"it","Vatican|Holy See|Pope|Pontiff|papal"),
 # ---- Asia ----
 ("AF","Afghanistan","Asia",33.94,67.71,"Kabul",34.53,69.17,"en","Afghan|Afghans|Taliban|Kandahar"),
 ("AM","Armenia","Asia",40.07,45.04,"Yerevan",40.18,44.51,"hy","Armenian|Armenians|Nagorno-Karabakh|Karabakh"),
 ("AZ","Azerbaijan","Asia",40.14,47.58,"Baku",40.41,49.87,"az","Azerbaijani|Azeri|Aliyev"),
 ("BH","Bahrain","Asia",26.07,50.55,"Manama",26.23,50.59,"en","Bahraini"),
 ("BD","Bangladesh","Asia",23.68,90.36,"Dhaka",23.81,90.41,"en","Bangladeshi|Rohingya|Cox's Bazar"),
 ("BT","Bhutan","Asia",27.51,90.43,"Thimphu",27.47,89.64,"en","Bhutanese"),
 ("BN","Brunei","Asia",4.54,114.73,"Bandar Seri Begawan",4.94,114.95,"en","Bruneian"),
 ("KH","Cambodia","Asia",12.57,104.99,"Phnom Penh",11.56,104.92,"en","Cambodian|Khmer|Hun Sen|Hun Manet"),
 ("CN","China","Asia",35.86,104.20,"Beijing",39.90,116.41,"zh-CN","Chinese|PRC|Xi Jinping|Shanghai|Shenzhen|Guangzhou|Xinjiang|Tibet|Hong Kong|Macau|Macao|Chine|Chinesisch|中国|北京|习近平|Zhongnanhai|CCP"),
 ("GE","Georgia","Asia",42.32,43.36,"Tbilisi",41.72,44.83,"ka","Georgian|Tbilisi|Abkhazia|South Ossetia"),
 ("IN","India","Asia",20.59,78.96,"New Delhi",28.61,77.21,"en","Indian|Indians|Delhi|Mumbai|Bengaluru|Bangalore|Chennai|Kolkata|Hyderabad|Modi|Kashmir|Lok Sabha|Inde|Indien"),
 ("ID","Indonesia","Asia",-0.79,113.92,"Jakarta",-6.21,106.85,"id","Indonesian|Prabowo|Bali|Sumatra|Java|Papua|Nusantara"),
 ("IR","Iran","Asia",32.43,53.69,"Tehran",35.69,51.39,"fa","Iranian|Iranians|Tehran|Khamenei|IRGC|Islamic Republic|Isfahan|Natanz|Persian"),
 ("IQ","Iraq","Asia",33.22,43.68,"Baghdad",33.32,44.37,"ar","Iraqi|Iraqis|Kurdistan|Erbil|Mosul|Basra|Kirkuk"),
 ("IL","Israel","Asia",31.05,34.85,"Jerusalem",31.77,35.22,"en","Israeli|Israelis|Netanyahu|Tel Aviv|IDF|Knesset|Haifa|Israël"),
 ("JP","Japan","Asia",36.20,138.25,"Tokyo",35.68,139.69,"ja","Japanese|Tokyo|Osaka|Okinawa|Kyoto|Hiroshima|Japon|日本|東京"),
 ("JO","Jordan","Asia",30.59,36.24,"Amman",31.95,35.93,"ar","Jordanian|Jordanians"),
 ("KZ","Kazakhstan","Asia",48.02,66.92,"Astana",51.17,71.45,"ru","Kazakh|Kazakhstani|Almaty|Tokayev"),
 ("KW","Kuwait","Asia",29.31,47.48,"Kuwait City",29.38,47.99,"ar","Kuwaiti"),
 ("KG","Kyrgyzstan","Asia",41.20,74.77,"Bishkek",42.87,74.59,"ru","Kyrgyz|Kyrgyzstani"),
 ("LA","Laos","Asia",19.86,102.50,"Vientiane",17.97,102.63,"en","Lao|Laotian"),
 ("LB","Lebanon","Asia",33.85,35.86,"Beirut",33.89,35.50,"ar","Lebanese|Hezbollah|Beirut|Liban"),
 ("MY","Malaysia","Asia",4.21,101.98,"Kuala Lumpur",3.14,101.69,"en","Malaysian|Malaysians|Anwar Ibrahim|Sabah|Sarawak|Penang"),
 ("MV","Maldives","Asia",3.20,73.22,"Malé",4.18,73.51,"en","Maldivian|Male"),
 ("MN","Mongolia","Asia",46.86,103.85,"Ulaanbaatar",47.89,106.91,"mn","Mongolian"),
 ("MM","Myanmar","Asia",21.91,95.96,"Naypyidaw",19.76,96.08,"my","Burmese|Burma|Yangon|Rakhine|Naypyitaw"),
 ("NP","Nepal","Asia",28.39,84.12,"Kathmandu",27.72,85.32,"ne","Nepali|Nepalese|Everest"),
 ("KP","North Korea","Asia",40.34,127.51,"Pyongyang",39.02,125.75,"ko","North Korean|DPRK|Kim Jong Un|Kim Jong-un|Pyongyang"),
 ("OM","Oman","Asia",21.51,55.92,"Muscat",23.59,58.41,"ar","Omani"),
 ("PK","Pakistan","Asia",30.38,69.35,"Islamabad",33.68,73.05,"en","Pakistani|Pakistanis|Karachi|Lahore|Balochistan|Khyber|Peshawar|Rawalpindi|Imran Khan"),
 ("PS","Palestine","Asia",31.95,35.23,"Ramallah",31.90,35.20,"ar","Palestinian|Palestinians|Gaza|West Bank|Rafah|Hamas|Khan Younis|Jenin|Nablus|Hebron"),
 ("PH","Philippines","Asia",12.88,121.77,"Manila",14.60,120.98,"en","Philippine|Filipino|Filipinos|Marcos|Mindanao|Cebu|Davao|Luzon"),
 ("QA","Qatar","Asia",25.35,51.18,"Doha",25.29,51.53,"en","Qatari|Doha"),
 ("SA","Saudi Arabia","Asia",23.89,45.08,"Riyadh",24.71,46.68,"ar","Saudi|Saudis|Riyadh|Jeddah|Mecca|Makkah|Medina|MBS|Mohammed bin Salman|Arabie saoudite"),
 ("SG","Singapore","Asia",1.35,103.82,"Singapore",1.29,103.85,"en","Singaporean|Singaporeans"),
 ("KR","South Korea","Asia",35.91,127.77,"Seoul",37.57,126.98,"ko","South Korean|Korean|Koreans|Seoul|Busan|ROK|Corée du Sud"),
 ("LK","Sri Lanka","Asia",7.87,80.77,"Colombo",6.93,79.85,"en","Sri Lankan|Ceylon|Colombo"),
 ("SY","Syria","Asia",34.80,38.99,"Damascus",33.51,36.29,"ar","Syrian|Syrians|Damascus|Aleppo|Idlib|Homs|Latakia|al-Sharaa|Syrie"),
 ("TW","Taiwan","Asia",23.70,120.96,"Taipei",25.03,121.57,"zh-TW","Taiwanese|Taipei|Lai Ching-te|Kaohsiung|台灣|台湾|台北"),
 ("TJ","Tajikistan","Asia",38.86,71.28,"Dushanbe",38.56,68.77,"ru","Tajik"),
 ("TH","Thailand","Asia",15.87,100.99,"Bangkok",13.76,100.50,"th","Thai|Thais|Bangkok|Phuket|Chiang Mai"),
 ("TL","Timor-Leste","Asia",-8.87,125.73,"Dili",-8.56,125.58,"pt-PT","East Timor|Timorese"),
 ("TR","Turkey","Asia",38.96,35.24,"Ankara",39.93,32.87,"tr","Türkiye|Turkiye|Turkish|Turks|Erdogan|Erdoğan|Istanbul|Ankara|Izmir|Turquie|Türkei"),
 ("TM","Turkmenistan","Asia",38.97,59.56,"Ashgabat",37.96,58.33,"ru","Turkmen"),
 ("AE","United Arab Emirates","Asia",23.42,53.85,"Abu Dhabi",24.45,54.38,"en","UAE|Emirati|Emirates|Dubai|Abu Dhabi|Sharjah"),
 ("UZ","Uzbekistan","Asia",41.38,64.59,"Tashkent",41.30,69.24,"ru","Uzbek|Uzbekistani|Samarkand"),
 ("VN","Vietnam","Asia",14.06,108.28,"Hanoi",21.03,105.85,"vi","Vietnamese|Hanoi|Ho Chi Minh City|Saigon|Viet Nam|Việt Nam"),
 ("YE","Yemen","Asia",15.55,48.52,"Sanaa",15.37,44.19,"ar","Yemeni|Yemenis|Houthi|Houthis|Sana'a|Aden|Hodeidah|Hudaydah"),
 # ---- Africa ----
 ("DZ","Algeria","Africa",28.03,1.66,"Algiers",36.75,3.06,"fr","Algerian|Algerians|Alger|Algérie|Tebboune"),
 ("AO","Angola","Africa",-11.20,17.87,"Luanda",-8.84,13.23,"pt-PT","Angolan|Angolans"),
 ("BJ","Benin","Africa",9.31,2.32,"Porto-Novo",6.50,2.60,"fr","Beninese|Cotonou|Bénin"),
 ("BW","Botswana","Africa",-22.33,24.68,"Gaborone",-24.63,25.92,"en","Botswanan|Batswana|Motswana"),
 ("BF","Burkina Faso","Africa",12.24,-1.56,"Ouagadougou",12.37,-1.52,"fr","Burkinabe|Burkinabè|Traoré"),
 ("BI","Burundi","Africa",-3.37,29.92,"Gitega",-3.43,29.93,"fr","Burundian|Bujumbura"),
 ("CV","Cabo Verde","Africa",16.00,-24.01,"Praia",14.93,-23.51,"pt-PT","Cape Verde|Cape Verdean|Cabo Verdean"),
 ("CM","Cameroon","Africa",7.37,12.35,"Yaoundé",3.87,11.52,"fr","Cameroonian|Cameroonians|Yaounde|Douala|Biya|Cameroun"),
 ("CF","Central African Republic","Africa",6.61,20.94,"Bangui",4.39,18.56,"fr","Centrafrique|CAR|Central African"),
 ("TD","Chad","Africa",15.45,18.73,"N'Djamena",12.13,15.06,"fr","Chadian|Chadians|Ndjamena|Tchad|Déby|Deby"),
 ("KM","Comoros","Africa",-11.65,43.33,"Moroni",-11.70,43.26,"fr","Comorian|Comores"),
 ("CD","Democratic Republic of the Congo","Africa",-4.04,21.76,"Kinshasa",-4.44,15.27,"fr","DRC|DR Congo|Congolese|Kinshasa|Goma|Bukavu|Kivu|M23|Tshisekedi|RDC|Congo-Kinshasa"),
 ("CG","Republic of the Congo","Africa",-0.23,15.83,"Brazzaville",-4.27,15.28,"fr","Congo-Brazzaville|Brazzaville|Sassou"),
 ("CI","Côte d'Ivoire","Africa",7.54,-5.55,"Yamoussoukro",6.83,-5.29,"fr","Ivory Coast|Ivorian|Ivorians|Abidjan|Cote d'Ivoire|Ouattara"),
 ("DJ","Djibouti","Africa",11.83,42.59,"Djibouti",11.59,43.15,"fr","Djiboutian"),
 ("EG","Egypt","Africa",26.82,30.80,"Cairo",30.04,31.24,"ar","Egyptian|Egyptians|Cairo|Sisi|Sinai|Suez|Alexandria|Égypte|Egipto"),
 ("GQ","Equatorial Guinea","Africa",1.65,10.27,"Malabo",3.75,8.78,"es","Equatoguinean|Obiang"),
 ("ER","Eritrea","Africa",15.18,39.78,"Asmara",15.34,38.93,"en","Eritrean|Eritreans|Isaias"),
 ("SZ","Eswatini","Africa",-26.52,31.47,"Mbabane",-26.32,31.13,"en","Swaziland|Swazi|Mswati"),
 ("ET","Ethiopia","Africa",9.15,40.49,"Addis Ababa",9.02,38.75,"en","Ethiopian|Ethiopians|Addis|Tigray|Amhara|Oromia|Abiy"),
 ("GA","Gabon","Africa",-0.80,11.61,"Libreville",0.39,9.45,"fr","Gabonese|Oligui"),
 ("GM","Gambia","Africa",13.44,-15.31,"Banjul",13.45,-16.58,"en","Gambian|Gambians|The Gambia"),
 ("GH","Ghana","Africa",7.95,-1.02,"Accra",5.60,-0.19,"en","Ghanaian|Ghanaians|Accra|Kumasi|Mahama"),
 ("GN","Guinea","Africa",9.95,-9.70,"Conakry",9.64,-13.58,"fr","Guinean|Guineans|Conakry|Doumbouya"),
 ("GW","Guinea-Bissau","Africa",11.80,-15.18,"Bissau",11.86,-15.60,"pt-PT","Bissau-Guinean|Embaló"),
 ("KE","Kenya","Africa",-0.02,37.91,"Nairobi",-1.29,36.82,"en","Kenyan|Kenyans|Nairobi|Mombasa|Ruto"),
 ("LS","Lesotho","Africa",-29.61,28.23,"Maseru",-29.31,27.48,"en","Basotho|Mosotho"),
 ("LR","Liberia","Africa",6.43,-9.43,"Monrovia",6.30,-10.80,"en","Liberian|Liberians|Boakai"),
 ("LY","Libya","Africa",26.34,17.23,"Tripoli",32.89,13.19,"ar","Libyan|Libyans|Tripoli|Benghazi|Haftar|Misrata|Libye"),
 ("MG","Madagascar","Africa",-18.77,46.87,"Antananarivo",-18.88,47.51,"fr","Malagasy|Rajoelina"),
 ("MW","Malawi","Africa",-13.25,34.30,"Lilongwe",-13.96,33.77,"en","Malawian|Malawians|Blantyre|Chakwera"),
 ("ML","Mali","Africa",17.57,-4.00,"Bamako",12.64,-8.00,"fr","Malian|Malians|Bamako|Timbuktu|Gao|Goïta|Goita"),
 ("MR","Mauritania","Africa",21.01,-10.94,"Nouakchott",18.09,-15.98,"fr","Mauritanian|Mauritanie"),
 ("MU","Mauritius","Africa",-20.35,57.55,"Port Louis",-20.16,57.50,"en","Mauritian|Maurice"),
 ("MA","Morocco","Africa",31.79,-7.09,"Rabat",34.02,-6.84,"fr","Moroccan|Moroccans|Casablanca|Marrakech|Western Sahara|Maroc|Marruecos|Polisario"),
 ("MZ","Mozambique","Africa",-18.67,35.53,"Maputo",-25.97,32.57,"pt-PT","Mozambican|Mozambicans|Cabo Delgado|Chapo"),
 ("NA","Namibia","Africa",-22.96,18.49,"Windhoek",-22.56,17.08,"en","Namibian|Namibians"),
 ("NE","Niger","Africa",17.61,8.08,"Niamey",13.51,2.11,"fr","Nigerien|Nigeriens|Niamey|Tiani|Tchiani"),
 ("NG","Nigeria","Africa",9.08,8.68,"Abuja",9.06,7.49,"en","Nigerian|Nigerians|Lagos|Abuja|Kano|Tinubu|Boko Haram|Kaduna|Borno|Port Harcourt"),
 ("RW","Rwanda","Africa",-1.94,29.87,"Kigali",-1.94,30.06,"en","Rwandan|Rwandans|Kagame"),
 ("ST","São Tomé and Príncipe","Africa",0.19,6.61,"São Tomé",0.34,6.73,"pt-PT","Sao Tome|São Tomé"),
 ("SN","Senegal","Africa",14.50,-14.45,"Dakar",14.69,-17.44,"fr","Senegalese|Dakar|Sénégal|Faye|Sonko"),
 ("SC","Seychelles","Africa",-4.68,55.49,"Victoria",-4.62,55.45,"en","Seychellois"),
 ("SL","Sierra Leone","Africa",8.46,-11.78,"Freetown",8.49,-13.23,"en","Sierra Leonean|Freetown"),
 ("SO","Somalia","Africa",5.15,46.20,"Mogadishu",2.05,45.32,"en","Somali|Somalis|Mogadishu|al-Shabaab|Al-Shabab|Somaliland|Puntland|Hargeisa"),
 ("ZA","South Africa","Africa",-30.56,22.94,"Pretoria",-25.75,28.19,"en","South African|South Africans|Johannesburg|Cape Town|Durban|Ramaphosa|Pretoria|Afrique du Sud|Sudáfrica"),
 ("SS","South Sudan","Africa",6.88,31.31,"Juba",4.86,31.57,"en","South Sudanese|Juba|Salva Kiir|Machar"),
 ("SD","Sudan","Africa",12.86,30.22,"Khartoum",15.50,32.56,"ar","Sudanese|Khartoum|Darfur|El Fasher|RSF|Rapid Support Forces|Port Sudan|Burhan|Hemedti|Soudan|Sudán"),
 ("TZ","Tanzania","Africa",-6.37,34.89,"Dodoma",-6.16,35.75,"en","Tanzanian|Tanzanians|Dar es Salaam|Zanzibar|Samia Suluhu"),
 ("TG","Togo","Africa",8.62,0.82,"Lomé",6.13,1.22,"fr","Togolese|Lome|Gnassingbé"),
 ("TN","Tunisia","Africa",33.89,9.54,"Tunis",36.81,10.18,"fr","Tunisian|Tunisians|Tunis|Saied|Tunisie|Túnez"),
 ("UG","Uganda","Africa",1.37,32.29,"Kampala",0.35,32.58,"en","Ugandan|Ugandans|Kampala|Museveni"),
 ("ZM","Zambia","Africa",-13.13,27.85,"Lusaka",-15.39,28.32,"en","Zambian|Zambians|Lusaka|Hichilema"),
 ("ZW","Zimbabwe","Africa",-19.02,29.15,"Harare",-17.83,31.05,"en","Zimbabwean|Zimbabweans|Harare|Bulawayo|Mnangagwa"),
 # ---- Americas ----
 ("AG","Antigua and Barbuda","Americas",17.06,-61.80,"St. John's",17.12,-61.85,"en","Antiguan|Antigua|Barbuda"),
 ("AR","Argentina","Americas",-38.42,-63.62,"Buenos Aires",-34.60,-58.38,"es-419","Argentine|Argentinian|Argentinians|Argentines|Milei|Buenos Aires|Argentinien|Argentine"),
 ("BS","Bahamas","Americas",25.03,-77.40,"Nassau",25.05,-77.34,"en","Bahamian|Bahamians|Nassau"),
 ("BB","Barbados","Americas",13.19,-59.54,"Bridgetown",13.10,-59.62,"en","Barbadian|Bajan|Mottley"),
 ("BZ","Belize","Americas",17.19,-88.50,"Belmopan",17.25,-88.77,"en","Belizean"),
 ("BO","Bolivia","Americas",-16.29,-63.59,"La Paz",-16.50,-68.15,"es-419","Bolivian|Bolivians|La Paz|Santa Cruz de la Sierra|Sucre"),
 ("BR","Brazil","Americas",-14.24,-51.93,"Brasília",-15.79,-47.88,"pt-BR","Brazilian|Brazilians|Brasil|Brasilia|São Paulo|Sao Paulo|Rio de Janeiro|Lula|Bolsonaro|Amazon rainforest|Brésil|Brasilien"),
 ("CA","Canada","Americas",56.13,-106.35,"Ottawa",45.42,-75.70,"en","Canadian|Canadians|Ottawa|Toronto|Vancouver|Montreal|Montréal|Quebec|Québec|Alberta|Ontario|Carney|Kanada"),
 ("CL","Chile","Americas",-35.68,-71.54,"Santiago",-33.45,-70.67,"es-419","Chilean|Chileans|Santiago de Chile|Boric|Chili"),
 ("CO","Colombia","Americas",4.57,-74.30,"Bogotá",4.71,-74.07,"es-419","Colombian|Colombians|Bogota|Medellín|Medellin|Cali|Petro|ELN|Colombie|Kolumbien"),
 ("CR","Costa Rica","Americas",9.75,-83.75,"San José",9.93,-84.08,"es-419","Costa Rican|Costa Ricans|San Jose"),
 ("CU","Cuba","Americas",21.52,-77.78,"Havana",23.11,-82.37,"es-419","Cuban|Cubans|Havana|La Habana|Díaz-Canel|Guantánamo|Guantanamo"),
 ("DM","Dominica","Americas",15.41,-61.37,"Roseau",15.30,-61.39,"en","Roseau|Commonwealth of Dominica"),
 ("DO","Dominican Republic","Americas",18.74,-70.16,"Santo Domingo",18.49,-69.93,"es-419","Dominican|Dominicans|Santo Domingo|Abinader|Punta Cana"),
 ("EC","Ecuador","Americas",-1.83,-78.18,"Quito",-0.18,-78.47,"es-419","Ecuadorian|Ecuadorians|Ecuadorean|Quito|Guayaquil|Noboa|Galápagos|Galapagos|Équateur"),
 ("SV","El Salvador","Americas",13.79,-88.90,"San Salvador",13.69,-89.19,"es-419","Salvadoran|Salvadorans|Salvadorean|Bukele"),
 ("GD","Grenada","Americas",12.12,-61.68,"St. George's",12.06,-61.75,"en","Grenadian"),
 ("GT","Guatemala","Americas",15.78,-90.23,"Guatemala City",14.63,-90.51,"es-419","Guatemalan|Guatemalans|Arévalo|Arevalo"),
 ("GY","Guyana","Americas",4.86,-58.93,"Georgetown",6.80,-58.16,"en","Guyanese|Georgetown|Essequibo"),
 ("HT","Haiti","Americas",18.97,-72.29,"Port-au-Prince",18.54,-72.34,"fr","Haitian|Haitians|Port-au-Prince|Haïti"),
 ("HN","Honduras","Americas",15.20,-86.24,"Tegucigalpa",14.07,-87.19,"es-419","Honduran|Hondurans|San Pedro Sula"),
 ("JM","Jamaica","Americas",18.11,-77.30,"Kingston",17.97,-76.79,"en","Jamaican|Jamaicans|Kingston|Holness"),
 ("MX","Mexico","Americas",23.63,-102.55,"Mexico City",19.43,-99.13,"es-419","Mexican|Mexicans|México|Sheinbaum|Guadalajara|Monterrey|Sinaloa|Tijuana|Ciudad Juárez|Juarez|Cancún|Cancun|Chiapas|Mexique|Mexiko"),
 ("NI","Nicaragua","Americas",12.87,-85.21,"Managua",12.11,-86.24,"es-419","Nicaraguan|Nicaraguans|Ortega|Managua"),
 ("PA","Panama","Americas",8.54,-80.78,"Panama City",8.98,-79.52,"es-419","Panamanian|Panamanians|Panamá|Panama Canal|Mulino"),
 ("PY","Paraguay","Americas",-23.44,-58.44,"Asunción",-25.26,-57.58,"es-419","Paraguayan|Paraguayans|Asuncion|Peña"),
 ("PE","Peru","Americas",-9.19,-75.02,"Lima",-12.05,-77.04,"es-419","Peruvian|Peruvians|Perú|Lima|Cusco|Machu Picchu|Pérou"),
 ("KN","Saint Kitts and Nevis","Americas",17.36,-62.78,"Basseterre",17.30,-62.72,"en","St Kitts|St. Kitts|Kittitian|Nevis"),
 ("LC","Saint Lucia","Americas",13.91,-60.98,"Castries",14.01,-60.99,"en","St Lucia|St. Lucia|Saint Lucian"),
 ("VC","Saint Vincent and the Grenadines","Americas",12.98,-61.29,"Kingstown",13.16,-61.22,"en","St Vincent|St. Vincent|Vincentian|Grenadines"),
 ("SR","Suriname","Americas",3.92,-56.03,"Paramaribo",5.85,-55.20,"nl","Surinamese|Paramaribo"),
 ("TT","Trinidad and Tobago","Americas",10.69,-61.22,"Port of Spain",10.65,-61.52,"en","Trinidad|Trinidadian|Tobago"),
 ("US","United States","Americas",37.09,-95.71,"Washington",38.91,-77.04,"en","US|U.S.|USA|U.S.A.|America|American|Americans|Washington|White House|Pentagon|Capitol Hill|Trump|Vance|New York|Los Angeles|California|Texas|Florida|Chicago|Wall Street|Silicon Valley|Fed|Federal Reserve|SCOTUS|Supreme Court|Etats-Unis|États-Unis|Estados Unidos|USA|Vereinigte Staaten|Estados Unidos|EE.UU.|EEUU"),
 ("UY","Uruguay","Americas",-32.52,-55.77,"Montevideo",-34.90,-56.16,"es-419","Uruguayan|Uruguayans|Orsi"),
 ("VE","Venezuela","Americas",6.42,-66.59,"Caracas",10.49,-66.88,"es-419","Venezuelan|Venezuelans|Caracas|Maduro|Machado|Chavista"),
 # ---- Oceania ----
 ("AU","Australia","Oceania",-25.27,133.78,"Canberra",-35.28,149.13,"en","Australian|Australians|Aussie|Sydney|Melbourne|Brisbane|Perth|Adelaide|Canberra|Queensland|Albanese|Australie|Australien"),
 ("FJ","Fiji","Oceania",-17.71,178.07,"Suva",-18.14,178.44,"en","Fijian|Fijians|Suva|Rabuka"),
 ("KI","Kiribati","Oceania",1.87,-157.36,"Tarawa",1.45,173.03,"en","I-Kiribati|Tarawa"),
 ("MH","Marshall Islands","Oceania",7.13,171.18,"Majuro",7.09,171.38,"en","Marshallese|Majuro"),
 ("FM","Micronesia","Oceania",6.89,158.22,"Palikir",6.92,158.16,"en","Micronesian|Pohnpei|Chuuk"),
 ("NR","Nauru","Oceania",-0.52,166.93,"Yaren",-0.55,166.92,"en","Nauruan"),
 ("NZ","New Zealand","Oceania",-40.90,174.89,"Wellington",-41.29,174.78,"en","New Zealander|Kiwi|Kiwis|Aotearoa|Auckland|Wellington|Christchurch|Luxon|Māori|Maori|Nouvelle-Zélande|Neuseeland"),
 ("PW","Palau","Oceania",7.51,134.58,"Ngerulmud",7.50,134.62,"en","Palauan|Koror"),
 ("PG","Papua New Guinea","Oceania",-6.31,143.96,"Port Moresby",-9.44,147.18,"en","PNG|Papua New Guinean|Port Moresby|Bougainville|Marape"),
 ("WS","Samoa","Oceania",-13.76,-172.10,"Apia",-13.83,-171.77,"en","Samoan|Samoans|Apia"),
 ("SB","Solomon Islands","Oceania",-9.65,160.16,"Honiara",-9.43,159.95,"en","Solomon Islander|Honiara"),
 ("TO","Tonga","Oceania",-21.18,-175.20,"Nuku'alofa",-21.14,-175.20,"en","Tongan|Tongans|Nukualofa"),
 ("TV","Tuvalu","Oceania",-7.11,177.65,"Funafuti",-8.52,179.20,"en","Tuvaluan|Funafuti"),
 ("VU","Vanuatu","Oceania",-15.38,166.96,"Port Vila",-17.73,168.32,"en","Ni-Vanuatu|Port Vila"),
]

# Countries with an official English Google News edition (used for hl/ceid).
GNEWS_ENGLISH_EDITIONS = {
    "US","GB","IE","CA","AU","NZ","IN","PK","ZA","NG","KE","GH","SG","MY","PH","IL","AE","ET",
    "TZ","UG","ZW","BW","NA","LK","BD","LB","SA","EG","ID",
}

COUNTRY_BY_CODE = {c[0]: c for c in COUNTRIES}
COUNTRY_NAMES = {c[0]: c[1] for c in COUNTRIES}
REGION_BY_CODE = {c[0]: c[2] for c in COUNTRIES}

# Aliases that are ambiguous (plain English words or short acronyms) and must match case-sensitively / exactly.
CASE_SENSITIVE_ALIASES = {
    "US","U.S.","USA","U.S.A.","UK","U.K.","UAE","DRC","CAR","PNG","PRC","DPRK","ROK","IDF","IRGC",
    "RSF","ELN","CCP","M23","MBS","Fed","EU","England","Wales",
    "Georgia","Jordan","Chad","Niger","Guinea","Turkey","China","India","Male","Mali","Bali",
}

def gnews_feed_url(code: str) -> str:
    """National Google News edition RSS for a country."""
    c = COUNTRY_BY_CODE[code]
    lang = c[8]
    if code in GNEWS_ENGLISH_EDITIONS or lang == "en":
        hl, ceid_lang = f"en-{code}", "en"
    else:
        hl, ceid_lang = lang, lang.split("-")[0]
        if lang.startswith("pt-") or lang.startswith("es-") or lang.startswith("zh-"):
            ceid_lang = lang
    return f"https://news.google.com/rss?hl={hl}&gl={code}&ceid={code}:{ceid_lang}"

def gnews_search_url(code: str) -> str:
    """English Google News search feed for news *about* a country (adds foreign context)."""
    from urllib.parse import quote_plus
    name = COUNTRY_BY_CODE[code][1]
    return f"https://news.google.com/rss/search?q={quote_plus(name)}+when:2d&hl=en-US&gl=US&ceid=US:en"

# ---------------------------------------------------------------------------------------------
# Exonyms: how other languages name the countries that appear most in world news. These make
# foreign-language articles geolocate correctly and let the same story merge across languages.
# Format: code -> "name|name|..."  (es, fr, de, it, pt, and a few ru/tr/ar/zh where useful)
EXONYMS = {
 "US": "Estados Unidos|Etats-Unis|États-Unis|Vereinigte Staaten|Stati Uniti|EUA|EE.UU.|EEUU|USA|Amerika|Amérique|美国|США|ABD|الولايات المتحدة",
 "GB": "Reino Unido|Royaume-Uni|Großbritannien|Grossbritannien|Regno Unito|Gran Bretaña|Gran Bretagna|Inglaterra|Angleterre|Angleterre|Londres|Londra|英国|Великобритания|Birleşik Krallık|بريطانيا",
 "RU": "Rusia|Russie|Russland|Russia|Rússia|Rossiya|Moscú|Moscou|Moskau|Mosca|Moscovo|俄罗斯|Россия|Rusya|روسيا",
 "CN": "China|Chine|Chinesische|Cina|Pequim|Pekín|Pékin|Peking|Pechino|Cina|中国|Китай|Çin|الصين",
 "UA": "Ucrania|Ukraine|Ucraina|Ucrânia|Kiev|Kyiv|Kiew|Kijów|乌克兰|Украина|Ukrayna|أوكرانيا",
 "DE": "Alemania|Allemagne|Germania|Alemanha|Berlín|Berlino|Berlim|德国|Германия|Almanya|ألمانيا",
 "FR": "Francia|Frankreich|França|Paris|París|Parigi|Parigi|法国|Франция|Fransa|فرنسا",
 "IT": "Italia|Italie|Italien|Itália|Roma|Rom|Rome|意大利|Италия|İtalya|إيطاليا",
 "ES": "España|Espagne|Spanien|Spagna|Espanha|Madrid|西班牙|Испания|İspanya|إسبانيا",
 "IL": "Israël|Israel|Israele|Jerusalén|Jérusalem|Jerusalem|Gerusalemme|以色列|Израиль|İsrail|إسرائيل",
 "PS": "Palestina|Palestine|Palästina|Palestine|Gaza|Cisjordania|Cisjordanie|Westjordanland|Cisgiordania|巴勒斯坦|Палестина|Filistin|فلسطين",
 "IR": "Irán|Iran|Teherán|Téhéran|Teheran|伊朗|Иран|İran|إيران",
 "IQ": "Irak|Iraq|Bagdad|Bagdád|Baghdad|伊拉克|Ирак|العراق",
 "SY": "Siria|Syrie|Syrien|Síria|Damasco|Damas|Damaskus|叙利亚|Сирия|Suriye|سوريا",
 "LB": "Líbano|Liban|Libanon|Libano|Beirut|Beyrouth|黎巴嫩|Ливан|Lübnan|لبنان",
 "SA": "Arabia Saudí|Arabia Saudita|Arabie saoudite|Saudi-Arabien|Arabia Saudita|Arábia Saudita|Riad|Riyad|Riyadh|沙特|Саудовская Аравия|Suudi Arabistan|السعودية",
 "TR": "Turquía|Turquie|Türkei|Turchia|Turquia|Estambul|Istanbul|Istambul|Ankara|土耳其|Турция|تركيا",
 "EG": "Egipto|Égypte|Ägypten|Egitto|Egito|El Cairo|Le Caire|Kairo|Il Cairo|埃及|Египет|Mısır|مصر",
 "IN": "India|Inde|Indien|Índia|Nueva Delhi|New Delhi|Neu-Delhi|Nuova Delhi|印度|Индия|Hindistan|الهند",
 "PK": "Pakistán|Pakistan|Paquistão|Islamabad|巴基斯坦|Пакистан|باكستان",
 "JP": "Japón|Japon|Japan|Giappone|Japão|Tokio|Tokyo|Tokio|日本|Япония|Japonya|اليابان",
 "KR": "Corea del Sur|Corée du Sud|Südkorea|Corea del Sud|Coreia do Sul|Seúl|Séoul|Seoul|韩国|Южная Корея|Güney Kore|كوريا الجنوبية",
 "KP": "Corea del Norte|Corée du Nord|Nordkorea|Corea del Nord|Coreia do Norte|Pionyang|Pyongyang|朝鲜|Северная Корея|Kuzey Kore|كوريا الشمالية",
 "TW": "Taiwán|Taïwan|Taiwan|台湾|台灣|Тайвань|Tayvan|تايوان",
 "BR": "Brasil|Brésil|Brasilien|Brasile|Brasilia|Brasília|巴西|Бразилия|Brezilya|البرازيل",
 "MX": "México|Mexique|Mexiko|Messico|Ciudad de México|Mexico City|墨西哥|Мексика|Meksika|المكسيك",
 "AR": "Argentina|Argentine|Argentinien|Buenos Aires|阿根廷|Аргентина|Arjantin|الأرجنتين",
 "CA": "Canadá|Canada|Kanada|Ottawa|加拿大|Канада|Kanada|كندا",
 "AU": "Australia|Australie|Australien|Austrália|Canberra|澳大利亚|Австралия|Avustralya|أستراليا",
 "ZA": "Sudáfrica|Afrique du Sud|Südafrika|Sudafrica|África do Sul|南非|ЮАР|Güney Afrika|جنوب أفريقيا",
 "NG": "Nigeria|Nigéria|Nigerien|Abuya|Abuja|尼日利亚|Нигерия|Nijerya|نيجيريا",
 "ET": "Etiopía|Éthiopie|Äthiopien|Etiopia|Etiópia|Addis Abeba|埃塞俄比亚|Эфиопия|Etiyopya|إثيوبيا",
 "SD": "Sudán|Soudan|Sudan|Sudão|Jartum|Khartoum|Kartum|苏丹|Судан|Sudan|السودان",
 "CD": "República Democrática del Congo|République démocratique du Congo|Demokratische Republik Kongo|Repubblica Democratica del Congo|Congo|Kinshasa|刚果|Конго|Kongo|الكونغو",
 "KE": "Kenia|Kenya|Quênia|Nairobi|肯尼亚|Кения|Kenya|كينيا",
 "MA": "Marruecos|Maroc|Marokko|Marocco|Marrocos|Rabat|摩洛哥|Марокко|Fas|المغرب",
 "DZ": "Argelia|Algérie|Algerien|Algeria|Argélia|Argel|Alger|Algiers|阿尔及利亚|Алжир|Cezayir|الجزائر",
 "LY": "Libia|Libye|Libyen|Libya|Líbia|Trípoli|Tripoli|利比亚|Ливия|Libya|ليبيا",
 "VE": "Venezuela|Vénézuela|Caracas|委内瑞拉|Венесуэла|Venezuela|فنزويلا",
 "CO": "Colombia|Colombie|Kolumbien|Colômbia|Bogotá|哥伦比亚|Колумбия|Kolombiya|كولومبيا",
 "CL": "Chile|Chili|Santiago|智利|Чили|Şili|تشيلي",
 "PE": "Perú|Pérou|Peru|Lima|秘鲁|Перу|بيرو",
 "CU": "Cuba|Kuba|La Habana|La Havane|Havanna|L'Avana|古巴|Куба|Küba|كوبا",
 "PL": "Polonia|Pologne|Polen|Polônia|Varsovia|Varsovie|Warschau|Varsavia|波兰|Польша|Polonya|بولندا",
 "NL": "Países Bajos|Pays-Bas|Niederlande|Paesi Bassi|Holanda|Ámsterdam|La Haya|La Haye|Den Haag|L'Aia|荷兰|Нидерланды|Hollanda|هولندا",
 "BE": "Bélgica|Belgique|Belgien|Belgio|Bruselas|Bruxelles|Brüssel|比利时|Бельгия|Belçika|بلجيكا",
 "SE": "Suecia|Suède|Schweden|Svezia|Suécia|Estocolmo|Stockholm|Stoccolma|瑞典|Швеция|İsveç|السويد",
 "NO": "Noruega|Norvège|Norwegen|Norvegia|Oslo|挪威|Норвегия|Norveç|النرويج",
 "DK": "Dinamarca|Danemark|Dänemark|Danimarca|Copenhague|Copenaghen|Kopenhagen|Groenlandia|Groenland|Grönland|Groenlândia|丹麦|Дания|Danimarka|الدنمارك",
 "FI": "Finlandia|Finlande|Finnland|Finlândia|Helsinki|芬兰|Финляндия|Finlandiya|فنلندا",
 "CH": "Suiza|Suisse|Schweiz|Svizzera|Suíça|Ginebra|Genève|Genf|Ginevra|Zúrich|瑞士|Швейцария|İsviçre|سويسرا",
 "AT": "Austria|Autriche|Österreich|Áustria|Viena|Vienne|Wien|Vienna|奥地利|Австрия|Avusturya|النمسا",
 "GR": "Grecia|Grèce|Griechenland|Grécia|Atenas|Athènes|Athen|Atene|希腊|Греция|Yunanistan|اليونان",
 "PT": "Portugal|Lisboa|Lisbonne|Lissabon|Lisbona|葡萄牙|Португалия|Portekiz|البرتغال",
 "IE": "Irlanda|Irlande|Irland|Dublín|Dublin|Dublino|爱尔兰|Ирландия|İrlanda|أيرلندا",
 "HU": "Hungría|Hongrie|Ungarn|Ungheria|Hungria|Budapest|匈牙利|Венгрия|Macaristan|المجر",
 "CZ": "República Checa|République tchèque|Tschechien|Repubblica Ceca|Chéquia|Praga|Prague|Prag|捷克|Чехия|Çekya|التشيك",
 "RO": "Rumanía|Rumania|Roumanie|Rumänien|Romania|Roménia|Bucarest|Bukarest|罗马尼亚|Румыния|Romanya|رومانيا",
 "RS": "Serbia|Serbie|Serbien|Sérvia|Belgrado|Belgrade|Belgrad|塞尔维亚|Сербия|Sırbistan|صربيا",
 "XK": "Kosovo|Kosovë|Косово|科索沃|كوسوفو",
 "BY": "Bielorrusia|Biélorussie|Weißrussland|Bielorussia|Bielorrússia|Minsk|白俄罗斯|Беларусь|Belarus|بيلاروسيا",
 "AF": "Afganistán|Afghanistan|Afeganistão|Kabul|Kaboul|阿富汗|Афганистан|Afganistan|أفغانستان",
 "YE": "Yemen|Yémen|Jemen|Iémen|Saná|Sanaa|也门|Йемен|Yemen|اليمن",
 "ID": "Indonesia|Indonésie|Indonesien|Indonésia|Yakarta|Jakarta|印度尼西亚|Индонезия|Endonezya|إندونيسيا",
 "PH": "Filipinas|Philippines|Philippinen|Filippine|Manila|Manille|菲律宾|Филиппины|Filipinler|الفلبين",
 "VN": "Vietnam|Viêt Nam|Việt Nam|Vietnã|Hanói|Hanoi|越南|Вьетнам|فيتنام",
 "TH": "Tailandia|Thaïlande|Thailand|Thailandia|Tailândia|Bangkok|泰国|Таиланд|Tayland|تايلاند",
 "MM": "Birmania|Birmanie|Myanmar|Mianmar|缅甸|Мьянма|Myanmar|ميانمار",
 "BD": "Bangladés|Bangladesh|Bangladesch|Daca|Dacca|Dhaka|孟加拉国|Бангладеш|بنغلاديش",
 "AE": "Emiratos Árabes Unidos|Émirats arabes unis|Vereinigte Arabische Emirate|Emirati Arabi Uniti|Emirados Árabes Unidos|Dubái|Doubaï|Dubai|阿联酋|ОАЭ|الإمارات",
 "QA": "Catar|Qatar|Katar|Doha|卡塔尔|Катар|قطر",
 "NZ": "Nueva Zelanda|Nouvelle-Zélande|Neuseeland|Nuova Zelanda|Nova Zelândia|新西兰|Новая Зеландия|Yeni Zelanda|نيوزيلندا",
 "AM": "Armenia|Arménie|Armenien|Armênia|Ereván|Erevan|Jerewan|亚美尼亚|Армения|Ermenistan|أرمينيا",
 "AZ": "Azerbaiyán|Azerbaïdjan|Aserbaidschan|Azerbaigian|Azerbaijão|Bakú|Bakou|Baku|阿塞拜疆|Азербайджан|Azerbaycan|أذربيجان",
 "GE": "Georgia|Géorgie|Georgien|Tiflis|Tbilisi|Tbilissi|格鲁吉亚|Грузия|Gürcistan|جورجيا",
 "KZ": "Kazajistán|Kazakhstan|Kasachstan|Kazakistan|Cazaquistão|Astaná|Astana|哈萨克斯坦|Казахстан|Kazakistan|كازاخستان",
 "SO": "Somalia|Somalie|Somalia|Somália|Mogadiscio|Mogadischu|索马里|Сомали|Somali|الصومال",
 "SS": "Sudán del Sur|Soudan du Sud|Südsudan|Sud Sudan|Sudão do Sul|Juba|南苏丹|Южный Судан|جنوب السودان",
 "MZ": "Mozambique|Mozambique|Mosambik|Mozambico|Moçambique|Maputo|莫桑比克|Мозамбик|موزمبيق",
 "ZW": "Zimbabue|Zimbabwe|Simbabwe|Zimbábue|Harare|津巴布韦|Зимбабве|زيمبابوي",
 "MY": "Malasia|Malaisie|Malaysia|Malesia|Malásia|Kuala Lumpur|马来西亚|Малайзия|Malezya|ماليزيا",
 "SG": "Singapur|Singapour|Singapur|Singapore|Cingapura|新加坡|Сингапур|Singapur|سنغافورة",
 "HT": "Haití|Haïti|Haiti|Puerto Príncipe|Port-au-Prince|海地|Гаити|هايتي",
 "EC": "Ecuador|Équateur|Ecuador|Equador|Quito|厄瓜多尔|Эквадор|الإكوادور",
 "BO": "Bolivia|Bolivie|Bolivien|Bolívia|La Paz|玻利维亚|Боливия|بوليفيا",
 "PY": "Paraguay|Paraguai|Asunción|巴拉圭|Парагвай|باراغواي",
 "UY": "Uruguay|Uruguai|Montevideo|Montevidéu|乌拉圭|Уругвай|أوروغواي",
 "PA": "Panamá|Panama|Panamá|巴拿马|Панама|بنما",
 "GT": "Guatemala|Guatemala|危地马拉|Гватемала|غواتيمالا",
 "NI": "Nicaragua|Nicarágua|Managua|尼加拉瓜|Никарагуа|نيكاراغوا",
 "SV": "El Salvador|Salvador|San Salvador|萨尔瓦多|Сальвадор|السلفادور",
 "CR": "Costa Rica|San José|哥斯达黎加|Коста-Рика|كوستاريكا",
 "DO": "República Dominicana|République dominicaine|Dominikanische Republik|Repubblica Dominicana|Santo Domingo|多米尼加|Доминиканская Республика",
 "JM": "Jamaica|Jamaïque|Jamaika|Giamaica|Kingston|牙买加|Ямайка",
 "NP": "Nepal|Népal|Nepal|Katmandú|Katmandou|Kathmandu|尼泊尔|Непал|نيبال",
 "LK": "Sri Lanka|Ceilán|Colombo|斯里兰卡|Шри-Ланка|سريلانكا",
 "KH": "Camboya|Cambodge|Kambodscha|Cambogia|Camboja|Nom Pen|Phnom Penh|柬埔寨|Камбоджа|كمبوديا",
 "UZ": "Uzbekistán|Ouzbékistan|Usbekistan|Uzbekistan|Uzbequistão|Taskent|Tachkent|Tashkent|乌兹别克斯坦|Узбекистан",
 "TN": "Túnez|Tunisie|Tunesien|Tunisia|Tunísia|突尼斯|Тунис|Tunus|تونس",
 "JO": "Jordania|Jordanie|Jordanien|Giordania|Jordânia|Amán|Amman|约旦|Иордания|Ürdün|الأردن",
 "KW": "Kuwait|Koweït|Kuwait|Kuwait|Cuaite|科威特|Кувейт|الكويت",
 "OM": "Omán|Oman|Oman|Mascate|Muscat|阿曼|Оман|عمان",
 "BH": "Baréin|Bahreïn|Bahrain|Bahrein|Manama|巴林|Бахрейн|البحرين",
}

def _append_exonyms():
    updated = []
    for c in COUNTRIES:
        code = c[0]
        extra = EXONYMS.get(code)
        if extra:
            aliases = c[9]
            have = {a.strip().lower() for a in aliases.split("|") if a.strip()}
            add = [a for a in extra.split("|") if a.strip() and a.strip().lower() not in have]
            c = c[:9] + ("|".join(filter(None, [aliases] + add)),)
        updated.append(c)
    return updated

COUNTRIES = _append_exonyms()
COUNTRY_BY_CODE = {c[0]: c for c in COUNTRIES}
COUNTRY_NAMES = {c[0]: c[1] for c in COUNTRIES}
REGION_BY_CODE = {c[0]: c[2] for c in COUNTRIES}

# Adjectival / demonym forms in other languages (inflected variants matter: the gazetteer matches whole tokens).
FOREIGN_DEMONYMS = {
 "US": "estadounidense|estadounidenses|norteamericano|norteamericana|américain|américaine|américains|américaines|amerikanisch|amerikanische|amerikanischen|statunitense|statunitensi|americano|americana|americani|americanos|американский|американская",
 "CN": "chino|china|chinos|chinois|chinoise|chinoises|chinesisch|chinesische|chinesischen|cinese|cinesi|chinês|chinesa|китайский|китайская|Çinli",
 "RU": "ruso|rusa|rusos|russe|russes|russisch|russische|russischen|russo|russa|russi|russos|российский|российская|Rus",
 "UA": "ucraniano|ucraniana|ucranianos|ukrainien|ukrainienne|ukrainiens|ukrainisch|ukrainische|ucraino|ucraina|ucraini|ucraniano|украинский|украинская|Ukraynalı",
 "DE": "alemán|alemana|alemanes|allemand|allemande|allemands|deutsch|deutsche|deutschen|tedesco|tedesca|tedeschi|alemão|alemã|немецкий|германский|Alman",
 "FR": "francés|francesa|franceses|français|française|französisch|französische|francese|francesi|francês|francesa|французский|Fransız",
 "GB": "británico|británica|británicos|britannique|britanniques|britisch|britische|britannico|britannica|britannici|britânico|британский|İngiliz",
 "IT": "italiano|italiana|italianos|italien|italienne|italiens|italienisch|italienische|italiani|итальянский|İtalyan",
 "ES": "español|española|españoles|espagnol|espagnole|spanisch|spanische|spagnolo|spagnola|espanhol|испанский|İspanyol",
 "IL": "israelí|israelíes|israélien|israélienne|israéliens|israelisch|israelische|israeliano|israeliana|israeliani|israelense|израильский|İsrailli|إسرائيلي",
 "IR": "iraní|iraníes|iranien|iranienne|iraniens|iranisch|iranische|iraniano|iraniana|iraniani|iraniano|иранский|İranlı|إيراني",
 "PS": "palestino|palestina|palestinos|palestinien|palestinienne|palestiniens|palästinensisch|palästinensische|palestinese|palestinesi|palestino|палестинский|Filistinli|فلسطيني",
 "IN": "indio|india|indios|indien|indienne|indiens|indisch|indische|indiano|indiana|indiani|indiano|индийский|Hintli|هندي",
 "JP": "japonés|japonesa|japoneses|japonais|japonaise|japanisch|japanische|giapponese|giapponesi|japonês|японский|Japon|ياباني",
 "TR": "turco|turca|turcos|turc|turque|turcs|türkisch|türkische|turchi|турецкий|تركي",
 "BR": "brasileño|brasileña|brésilien|brésilienne|brasilianisch|brasiliano|brasiliana|brasileiro|brasileira|бразильский|Brezilyalı",
 "MX": "mexicano|mexicana|mexicanos|mexicain|mexicaine|mexikanisch|messicano|messicana|мексиканский|Meksikalı",
 "AR": "argentino|argentina|argentinos|argentin|argentine|argentinisch|argentino|аргентинский",
 "SA": "saudí|saudíes|saudita|saoudien|saoudienne|saoudiens|saudisch|saudische|saudita|sauditi|саудовский|Suudi|سعودي",
 "EG": "egipcio|egipcia|égyptien|égyptienne|ägyptisch|ägyptische|egiziano|egiziana|egípcio|египетский|Mısırlı|مصري",
 "KR": "surcoreano|surcoreana|sud-coréen|sud-coréenne|südkoreanisch|sudcoreano|sudcoreana|sul-coreano|южнокорейский",
 "KP": "norcoreano|norcoreana|nord-coréen|nord-coréenne|nordkoreanisch|nordcoreano|norte-coreano|северокорейский",
 "PK": "paquistaní|pakistaní|pakistanais|pakistanaise|pakistanisch|pakistano|paquistanês|пакистанский|Pakistanlı|باكستاني",
 "CA": "canadiense|canadien|canadienne|kanadisch|canadese|canadesi|canadense|канадский|Kanadalı",
 "AU": "australiano|australiana|australien|australienne|australisch|australiani|австралийский|Avustralyalı",
 "PL": "polaco|polaca|polonais|polonaise|polnisch|polacco|polacca|polonês|польский|Polonyalı",
 "NL": "neerlandés|holandés|néerlandais|néerlandaise|niederländisch|olandese|olandesi|holandês|нидерландский|Hollandalı",
 "SY": "sirio|siria|sirios|syrien|syrienne|syriens|syrisch|syrische|siriano|siriana|сирийский|Suriyeli|سوري",
 "VE": "venezolano|venezolana|vénézuélien|venezolanisch|venezuelano|венесуэльский",
 "NG": "nigeriano|nigeriana|nigérian|nigérianne|nigerianisch|nigeriani|нигерийский",
 "ZA": "sudafricano|sudafricana|sud-africain|sud-africaine|südafrikanisch|sudafricani|sul-africano|южноафриканский",
 "ET": "etíope|éthiopien|éthiopienne|äthiopisch|etiope|etíope|эфиопский",
 "SD": "sudanés|sudanesa|soudanais|soudanaise|sudanesisch|sudanese|sudanesi|sudanês|суданский|سوداني",
 "AF": "afgano|afgana|afghan|afghane|afghanisch|afgano|afegão|афганский|أفغاني",
 "VN": "vietnamita|vietnamien|vietnamienne|vietnamesisch|vietnamita|вьетнамский",
 "ID": "indonesio|indonesia|indonésien|indonesisch|indonesiano|indonésio|индонезийский",
 "PH": "filipino|filipina|philippin|philippine|philippinisch|filippino|filippina|филиппинский",
 "TH": "tailandés|tailandesa|thaïlandais|thailändisch|thailandese|tailandês|тайский",
 "GR": "griego|griega|grec|grecque|griechisch|greco|greca|grego|греческий|Yunan",
 "PT": "portugués|portuguesa|portugais|portugaise|portugiesisch|portoghese|português|португальский",
 "SE": "sueco|sueca|suédois|suédoise|schwedisch|svedese|sueco|шведский|İsveçli",
 "NO": "noruego|noruega|norvégien|norvégienne|norwegisch|norvegese|norueguês|норвежский",
 "DK": "danés|danesa|danois|danoise|dänisch|dänische|danese|danesi|dinamarquês|groenlandés|groenlandais|grönländisch|датский|Danimarkalı",
 "FI": "finlandés|finlandesa|finlandais|finnisch|finlandese|finlandês|финский",
 "CH": "suizo|suiza|suisse|schweizerisch|svizzero|svizzera|suíço|швейцарский|İsviçreli",
 "AT": "austriaco|austríaco|autrichien|autrichienne|österreichisch|austriaco|austríaco|австрийский",
 "BE": "belga|belgas|belge|belges|belgisch|belga|бельгийский",
 "CU": "cubano|cubana|cubain|cubaine|kubanisch|cubano|кубинский",
 "CO": "colombiano|colombiana|colombien|colombienne|kolumbianisch|colombiano|колумбийский",
 "CL": "chileno|chilena|chilien|chilienne|chilenisch|cileno|cilena|чилийский",
 "PE": "peruano|peruana|péruvien|péruvienne|peruanisch|peruviano|перуанский",
 "TW": "taiwanés|taiwanesa|taïwanais|taïwanaise|taiwanesisch|taiwanese|тайваньский|Tayvanlı",
 "YE": "yemení|yemení|yéménite|jemenitisch|yemenita|iemenita|йеменский|يمني",
 "LB": "libanés|libanesa|libanais|libanaise|libanesisch|libanese|libanesi|libanês|ливанский|لبناني",
 "IQ": "iraquí|iraquíes|irakien|irakienne|irakisch|iracheno|irachena|iraquiano|иракский|عراقي",
 "QA": "catarí|qatarí|qatari|katarisch|qatariota|катарский|قطري",
 "AE": "emiratí|émirati|emiratisch|emiratino|эмиратский|إماراتي",
}

def _append_demonyms():
    updated = []
    for c in COUNTRIES:
        extra = FOREIGN_DEMONYMS.get(c[0])
        if extra:
            have = {a.strip().lower() for a in c[9].split("|") if a.strip()}
            add = [a for a in extra.split("|") if a.strip() and a.strip().lower() not in have]
            c = c[:9] + ("|".join(filter(None, [c[9]] + add)),)
        updated.append(c)
    return updated

COUNTRIES = _append_demonyms()
COUNTRY_BY_CODE = {c[0]: c for c in COUNTRIES}
COUNTRY_NAMES = {c[0]: c[1] for c in COUNTRIES}
REGION_BY_CODE = {c[0]: c[2] for c in COUNTRIES}
