"""Curated direct RSS outlets with editorial-position and ownership labels.

Tuple layout: (name, country, lang, leaning, ownership, tier, feed_url)
  leaning   : approximate editorial position. Labels are indicative, drawn from widely cited media-bias
              assessments and the outlet's own stated line; treat them as a reading aid, not a verdict.
  ownership : state | public-service | private | party | nonprofit | cooperative
  tier      : 1 = global wire / major international, 2 = major national, 3 = regional / niche / specialist
Dead feeds are harmless: the fetcher records failures and /api/sources reports feed health.
"""

OUTLETS = [
 # ---------------- Global / international ----------------
 ("UN News","UN","en","institutional","state",1,"https://news.un.org/feed/subscribe/en/news/all/rss.xml"),
 ("Euronews","EU","en","centrist","private",1,"https://www.euronews.com/rss"),
 ("Politico Europe","EU","en","centrist","private",2,"https://www.politico.eu/feed/"),
 ("Foreign Policy","US","en","liberal-internationalist","private",2,"https://foreignpolicy.com/feed/"),
 ("The Diplomat","JP","en","liberal","private",2,"https://thediplomat.com/feed/"),
 ("AllAfrica","ZA","en","aggregator","private",2,"https://allafrica.com/tools/headlines/rdf/latest/headlines.rdf"),
 ("The Africa Report","FR","en","centrist","private",2,"https://www.theafricareport.com/feed/"),
 ("Middle East Eye","GB","en","left-leaning","private",2,"https://www.middleeasteye.net/rss"),
 ("Middle East Monitor","GB","en","pro-Palestinian","nonprofit",3,"https://www.middleeastmonitor.com/feed/"),
 ("ReliefWeb (OCHA)","UN","en","humanitarian","state",1,"https://reliefweb.int/updates/rss.xml"),
 ("GDACS disaster alerts","UN","en","institutional","state",1,"https://www.gdacs.org/xml/rss.xml"),
 ("USGS earthquakes M4.5+","US","en","institutional","state",1,"https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/4.5_day.atom"),
 ("Crisis Group","BE","en","centrist","nonprofit",2,"https://www.crisisgroup.org/rss"),
 ("Nature","GB","en","science","private",1,"https://www.nature.com/nature.rss"),
 ("Science","US","en","science","nonprofit",1,"https://www.science.org/rss/news_current.xml"),
 ("New Scientist","GB","en","science","private",2,"https://www.newscientist.com/feed/home/"),
 ("Phys.org","GB","en","science","private",3,"https://phys.org/rss-feed/"),
 ("MIT Technology Review","US","en","technology","nonprofit",2,"https://www.technologyreview.com/feed/"),
 ("Ars Technica","US","en","technology","private",2,"https://feeds.arstechnica.com/arstechnica/index"),
 ("The Verge","US","en","technology","private",2,"https://www.theverge.com/rss/index.xml"),
 ("TechCrunch","US","en","technology","private",2,"https://techcrunch.com/feed/"),
 ("Wired","US","en","technology","private",2,"https://www.wired.com/feed/rss"),
 ("Hacker News front page","US","en","tech-community","nonprofit",3,"https://hnrss.org/frontpage"),
 ("Reddit r/worldnews","US","en","popular-opinion","private",3,"https://www.reddit.com/r/worldnews/.rss"),
 ("Reddit r/news","US","en","popular-opinion","private",3,"https://www.reddit.com/r/news/.rss"),
 ("Defense News","US","en","defence","private",2,"https://www.defensenews.com/arc/outboundfeeds/rss/?outputType=xml"),
 ("Breaking Defense","US","en","defence","private",3,"https://breakingdefense.com/feed/"),
 ("ArtNews","US","en","art-culture","private",3,"https://www.artnews.com/feed/"),
 ("Hyperallergic","US","en","art-culture","private",3,"https://hyperallergic.com/feed/"),
 ("Variety","US","en","entertainment","private",2,"https://variety.com/feed/"),
 ("Smithsonian History","US","en","history","nonprofit",3,"https://www.smithsonianmag.com/rss/history/"),
 ("Times Higher Education","GB","en","education","private",3,"https://www.timeshighereducation.com/feed"),
 ("CNBC World","US","en","business/free-market","private",2,"https://www.cnbc.com/id/100727362/device/rss/rss.html"),
 ("The Economist","GB","en","liberal/free-market","private",1,"https://www.economist.com/international/rss.xml"),
 # ---------------- United States ----------------
 ("New York Times World","US","en","liberal","private",1,"https://rss.nytimes.com/services/xml/rss/nyt/World.xml"),
 ("Wall Street Journal World","US","en","centre-right/business","private",1,"https://feeds.a-dj.com/rss/RSSWorldNews.xml"),
 ("Washington Post World","US","en","liberal","private",1,"https://feeds.washingtonpost.com/rss/world"),
 ("CNN World","US","en","liberal","private",1,"http://rss.cnn.com/rss/edition_world.rss"),
 ("Fox News World","US","en","conservative","private",1,"https://moxie.foxnews.com/google-publisher/world.xml"),
 ("NPR World","US","en","centre-left","public-service",1,"https://feeds.npr.org/1004/rss.xml"),
 ("Politico","US","en","centrist","private",2,"https://rss.politico.com/politics-news.xml"),
 ("Breitbart","US","en","populist-right","private",2,"http://feeds.feedburner.com/breitbart"),
 ("National Review","US","en","conservative","private",2,"https://www.nationalreview.com/feed/"),
 ("Reason","US","en","libertarian","nonprofit",2,"https://reason.com/feed"),
 ("Jacobin","US","en","socialist","private",2,"https://jacobin.com/feed"),
 ("The Nation","US","en","left","private",2,"https://www.thenation.com/feed/?post_type=article"),
 ("The Intercept","US","en","left","nonprofit",2,"https://theintercept.com/feed/?rss"),
 ("Voice of America","US","en","state-line","state",1,"https://www.voanews.com/api/zq$omekvi_"),
 ("The Hill","US","en","centrist","private",2,"https://thehill.com/feed/"),
 ("Axios","US","en","centrist","private",2,"https://api.axios.com/feed/"),
 ("Democracy Now!","US","en","left","nonprofit",3,"https://www.democracynow.org/democracynow.rss"),
 ("Washington Times","US","en","conservative","private",2,"https://www.washingtontimes.com/rss/headlines/news/world/"),
 # ---------------- United Kingdom / Ireland ----------------
 ("BBC News World","GB","en","centrist","public-service",1,"http://feeds.bbci.co.uk/news/world/rss.xml"),
 ("The Guardian World","GB","en","centre-left","private",1,"https://www.theguardian.com/world/rss"),
 ("The Telegraph","GB","en","conservative","private",1,"https://www.telegraph.co.uk/rss.xml"),
 ("Daily Mail","GB","en","populist-right","private",2,"https://www.dailymail.co.uk/news/index.rss"),
 ("The Independent","GB","en","centre-left","private",2,"https://www.independent.co.uk/news/world/rss"),
 ("Sky News","GB","en","centrist","private",1,"https://feeds.skynews.com/feeds/rss/world.xml"),
 ("The Spectator","GB","en","conservative","private",2,"https://www.spectator.co.uk/feed"),
 ("Morning Star","GB","en","socialist","cooperative",3,"https://morningstaronline.co.uk/rss.xml"),
 ("New Statesman","GB","en","centre-left","private",2,"https://www.newstatesman.com/feed"),
 ("RTÉ News","IE","en","centrist","public-service",2,"https://www.rte.ie/news/rss/news-headlines.xml"),
 ("The Irish Times","IE","en","centre-left/liberal","private",2,"https://www.irishtimes.com/arc/outboundfeeds/feed-irish-news/"),
 # ---------------- France / Benelux / DACH ----------------
 ("France 24","FR","en","centrist","state",1,"https://www.france24.com/en/rss"),
 ("RFI","FR","en","centrist","state",1,"https://www.rfi.fr/en/rss"),
 ("Le Monde (English)","FR","en","centre-left","private",1,"https://www.lemonde.fr/en/rss/une.xml"),
 ("Le Figaro","FR","fr","conservative","private",2,"https://www.lefigaro.fr/rss/figaro_actualites.xml"),
 ("Libération","FR","fr","left","private",2,"https://www.liberation.fr/arc/outboundfeeds/rss-all/?outputType=xml"),
 ("L'Humanité","FR","fr","communist","private",3,"https://www.humanite.fr/rss"),
 ("Deutsche Welle","DE","en","centrist","public-service",1,"https://rss.dw.com/xml/rss-en-all"),
 ("Der Spiegel International","DE","en","centre-left","private",1,"https://www.spiegel.de/international/index.rss"),
 ("Frankfurter Allgemeine","DE","de","conservative-liberal","private",2,"https://www.faz.net/rss/aktuell/"),
 ("Die Welt","DE","de","conservative","private",2,"https://www.welt.de/feeds/latest.rss"),
 ("Süddeutsche Zeitung","DE","de","centre-left","private",2,"https://rss.sueddeutsche.de/rss/Topthemen"),
 ("taz","DE","de","left-green","cooperative",3,"https://taz.de/!p4608;rss/"),
 ("junge Welt","DE","de","marxist","cooperative",3,"https://www.jungewelt.de/feeds/newsticker.rss"),
 ("SWI swissinfo","CH","en","centrist","public-service",2,"https://www.swissinfo.ch/eng/rss"),
 ("Neue Zürcher Zeitung","CH","de","liberal-conservative","private",2,"https://www.nzz.ch/recent.rss"),
 ("ORF","AT","de","centrist","public-service",2,"https://rss.orf.at/news.xml"),
 ("Der Standard","AT","de","centre-left","private",2,"https://www.derstandard.at/rss"),
 ("NOS","NL","nl","centrist","public-service",2,"https://feeds.nos.nl/nosnieuwsalgemeen"),
 ("De Telegraaf","NL","nl","populist-right","private",2,"https://www.telegraaf.nl/rss"),
 ("NRC","NL","nl","liberal","private",2,"https://www.nrc.nl/rss/"),
 ("VRT NWS","BE","nl","centrist","public-service",2,"https://www.vrt.be/vrtnws/nl.rss.articles.xml"),
 ("RTBF Info","BE","fr","centrist","public-service",2,"https://rss.rtbf.be/article/rss/highlight_rtbfinfo_info-accueil.xml?source=internal"),
 ("RTL Luxembourg","LU","fr","centrist","private",3,"https://5minutes.rtl.lu/rss"),
 # ---------------- Southern Europe ----------------
 ("ANSA","IT","it","centrist","cooperative",1,"https://www.ansa.it/sito/notizie/mondo/mondo_rss.xml"),
 ("Corriere della Sera","IT","it","centre-right/liberal","private",2,"https://xml2.corriereobjects.it/rss/homepage.xml"),
 ("la Repubblica","IT","it","centre-left","private",2,"https://www.repubblica.it/rss/homepage/rss2.0.xml"),
 ("Il Fatto Quotidiano","IT","it","populist-left","private",3,"https://www.ilfattoquotidiano.it/feed/"),
 ("Il Giornale","IT","it","right","private",3,"https://www.ilgiornale.it/arc/outboundfeeds/rss/?outputType=xml"),
 ("El País","ES","es","centre-left","private",1,"https://feeds.elpais.com/mrss-s/pages/ep/site/elpais.com/portada"),
 ("El Mundo","ES","es","centre-right","private",2,"https://e00-elmundo.uecdn.es/elmundo/rss/portada.xml"),
 ("ABC","ES","es","conservative","private",2,"https://www.abc.es/rss/2.0/portada/"),
 ("Público","ES","es","left","private",3,"https://www.publico.es/rss/"),
 ("Público (PT)","PT","pt","centre-left","private",2,"https://www.publico.pt/rss"),
 ("RTP Notícias","PT","pt","centrist","public-service",2,"https://www.rtp.pt/noticias/rss"),
 ("Kathimerini (English)","GR","en","centre-right","private",2,"https://www.ekathimerini.com/feed/"),
 ("ERT News","GR","el","centrist","public-service",2,"https://www.ertnews.gr/feed/"),
 ("Efsyn","GR","el","left","cooperative",3,"https://www.efsyn.gr/rss.xml"),
 ("Cyprus Mail","CY","en","centrist","private",3,"https://cyprus-mail.com/feed/"),
 ("Times of Malta","MT","en","centrist","private",3,"https://timesofmalta.com/?feed=rss2"),
 # ---------------- Nordics / Baltics ----------------
 ("SVT Nyheter","SE","sv","centrist","public-service",2,"https://www.svt.se/nyheter/rss.xml"),
 ("Dagens Nyheter","SE","sv","liberal","private",2,"https://www.dn.se/rss/"),
 ("Aftonbladet","SE","sv","social-democratic","private",2,"https://rss.aftonbladet.se/rss2/small/pages/sections/senastenytt/"),
 ("NRK","NO","no","centrist","public-service",2,"https://www.nrk.no/toppsaker.rss"),
 ("Aftenposten","NO","no","conservative-liberal","private",2,"https://www.aftenposten.no/rss"),
 ("DR Nyheder","DK","da","centrist","public-service",2,"https://www.dr.dk/nyheder/service/feeds/allenyheder"),
 ("Politiken","DK","da","centre-left","private",2,"https://politiken.dk/rss/senestenyt.rss"),
 ("Yle News","FI","en","centrist","public-service",2,"https://feeds.yle.fi/uutiset/v1/majorHeadlines/YLE_NEWS.rss"),
 ("Helsingin Sanomat","FI","fi","liberal","private",2,"https://www.hs.fi/rss/tuoreimmat.xml"),
 ("RÚV","IS","is","centrist","public-service",3,"https://www.ruv.is/rss/frettir"),
 ("Iceland Monitor","IS","en","centre-right","private",3,"https://icelandmonitor.mbl.is/rss/"),
 ("ERR News","EE","en","centrist","public-service",2,"https://news.err.ee/rss"),
 ("LSM English","LV","en","centrist","public-service",2,"https://eng.lsm.lv/rss/"),
 ("LRT English","LT","en","centrist","public-service",2,"https://www.lrt.lt/en/news-in-english?rss"),
 # ---------------- Central & Eastern Europe ----------------
 ("Notes from Poland","PL","en","centrist","nonprofit",2,"https://notesfrompoland.com/feed/"),
 ("Gazeta Wyborcza","PL","pl","liberal","private",2,"https://wyborcza.pl/pub/rss/najnowsze_wyborcza.xml"),
 ("Rzeczpospolita","PL","pl","centre-right","private",2,"https://www.rp.pl/rss_main"),
 ("TVP Info","PL","pl","state-line","public-service",2,"http://www.tvp.info/tvp.info/rss+xml.php"),
 ("wPolityce","PL","pl","national-conservative","private",3,"https://wpolityce.pl/rss"),
 ("ČT24","CZ","cs","centrist","public-service",2,"https://ct24.ceskatelevize.cz/rss/hlavni-zpravy"),
 ("Radio Prague International","CZ","en","centrist","public-service",3,"https://english.radio.cz/rss/all"),
 ("Hungary Today","HU","en","pro-government","private",2,"https://hungarytoday.hu/feed/"),
 ("Telex","HU","hu","liberal/independent","private",2,"https://telex.hu/rss"),
 ("Hirado.hu (MTI)","HU","hu","state-line","state",2,"https://hirado.hu/rss"),
 ("Slovak Spectator","SK","en","liberal","private",3,"https://spectator.sme.sk/rss"),
 ("Romania Insider","RO","en","centrist","private",3,"https://www.romania-insider.com/feed"),
 ("Digi24","RO","ro","centrist","private",2,"https://www.digi24.ro/rss"),
 ("Novinite","BG","en","centrist","private",3,"https://www.novinite.com/services/news_rdf.php"),
 ("BTA","BG","en","state-line","state",2,"https://www.bta.bg/en/rss"),
 ("Moldpres","MD","en","state-line","state",3,"https://www.moldpres.md/rss/en"),
 ("N1 Serbia","RS","sr","opposition/independent","private",2,"https://n1info.rs/feed/"),
 ("RTS","RS","sr","pro-government","public-service",2,"https://www.rts.rs/page/stories/sr/rss.html"),
 ("Balkan Insight","BA","en","liberal/independent","nonprofit",2,"https://balkaninsight.com/feed/"),
 ("Index.hr","HR","hr","liberal","private",2,"https://www.index.hr/rss"),
 ("HRT","HR","hr","centrist","public-service",2,"https://vijesti.hrt.hr/feed.xml"),
 ("Klix.ba","BA","bs","centrist","private",3,"https://www.klix.ba/rss"),
 ("STA","SI","en","centrist","state",3,"https://english.sta.si/rss"),
 ("MIA","MK","en","state-line","state",3,"https://mia.mk/feed"),
 ("Vijesti","ME","sr","liberal","private",3,"https://www.vijesti.me/rss"),
 ("Tirana Times","AL","en","centrist","private",3,"https://www.tiranatimes.com/?feed=rss2"),
 ("Kosovo Online","XK","en","centrist","private",3,"https://www.kosovo-online.com/rss.xml"),
 # ---------------- Russia / Ukraine / Belarus / Caucasus ----------------
 ("TASS","RU","en","state-line","state",1,"https://tass.com/rss/v2.xml"),
 ("RT","RU","en","state-line","state",1,"https://www.rt.com/rss/news/"),
 ("RIA Novosti","RU","ru","state-line","state",1,"https://ria.ru/export/rss2/archive/index.xml"),
 ("Interfax","RU","ru","centrist/business","private",2,"https://www.interfax.ru/rss.asp"),
 ("Kommersant","RU","ru","business","private",2,"https://www.kommersant.ru/RSS/news.xml"),
 ("Meduza","RU","en","liberal/independent (exiled)","private",2,"https://meduza.io/rss/all"),
 ("Novaya Gazeta Europe","RU","en","liberal/independent (exiled)","private",2,"https://novayagazeta.eu/feed/rss"),
 ("The Moscow Times","RU","en","liberal/independent (exiled)","private",2,"https://www.themoscowtimes.com/rss/news"),
 ("Ukrinform","UA","en","state-line","state",2,"https://www.ukrinform.net/rss/block-lastnews"),
 ("The Kyiv Independent","UA","en","liberal/independent","private",1,"https://kyivindependent.com/news-archive/rss/"),
 ("Ukrainska Pravda","UA","en","independent","private",2,"https://www.pravda.com.ua/eng/rss/"),
 ("Kyiv Post","UA","en","centrist","private",2,"https://www.kyivpost.com/feed"),
 ("BelTA","BY","en","state-line","state",2,"https://eng.belta.by/rss"),
 ("Civil.ge","GE","en","liberal/independent","nonprofit",2,"https://civil.ge/feed"),
 ("Agenda.ge","GE","en","pro-government","private",3,"https://agenda.ge/rss"),
 ("Armenpress","AM","en","state-line","state",2,"https://armenpress.am/eng/rss/"),
 ("News.am","AM","en","centrist","private",3,"https://news.am/eng/rss/"),
 ("Trend News Agency","AZ","en","pro-government","private",2,"https://www.trend.az/feeds/index.rss"),
 ("Azertac","AZ","en","state-line","state",2,"https://azertag.az/en/rss"),
 ("Report.az","AZ","en","pro-government","private",3,"https://report.az/en/rss/"),
 # ---------------- Turkey / Middle East ----------------
 ("Anadolu Agency","TR","en","state-line","state",1,"https://www.aa.com.tr/en/rss/default?cat=guncel"),
 ("Daily Sabah","TR","en","pro-government/conservative","private",2,"https://www.dailysabah.com/rssFeed/turkey"),
 ("Hürriyet Daily News","TR","en","centrist","private",2,"https://www.hurriyetdailynews.com/rss"),
 ("Duvar English","TR","en","opposition/left-liberal","private",3,"https://www.duvarenglish.com/rss"),
 ("Bianet","TR","en","left","nonprofit",3,"https://bianet.org/rss"),
 ("Al Jazeera English","QA","en","state-funded/pan-Arab","state",1,"https://www.aljazeera.com/xml/rss/all.xml"),
 ("The Peninsula","QA","en","pro-government","private",3,"https://thepeninsulaqatar.com/rss"),
 ("Al Arabiya English","SA","en","pro-Saudi-government","private",1,"https://english.alarabiya.net/feed/rss2/en.xml"),
 ("Arab News","SA","en","pro-government","private",1,"https://www.arabnews.com/rss.xml"),
 ("Saudi Gazette","SA","en","pro-government","private",3,"https://saudigazette.com.sa/rssFeed/74"),
 ("Gulf News","AE","en","pro-government","private",2,"https://gulfnews.com/rss"),
 ("The National","AE","en","pro-government","state",1,"https://www.thenationalnews.com/arc/outboundfeeds/rss/?outputType=xml"),
 ("Khaleej Times","AE","en","pro-government","private",2,"https://www.khaleejtimes.com/api/v1/collections/top-section.rss"),
 ("Times of Oman","OM","en","pro-government","private",3,"https://timesofoman.com/feed/"),
 ("KUNA","KW","en","state-line","state",3,"https://www.kuna.net.kw/rss.aspx?language=en"),
 ("Bahrain News Agency","BH","en","state-line","state",3,"https://www.bna.bh/en/rss"),
 ("The Times of Israel","IL","en","centrist","private",1,"https://www.timesofisrael.com/feed/"),
 ("Haaretz","IL","en","left-liberal","private",1,"https://www.haaretz.com/srv/haaretz-latest-headlines"),
 ("The Jerusalem Post","IL","en","centre-right","private",1,"https://www.jpost.com/rss/rssfeedsfrontpage.aspx"),
 ("Ynetnews","IL","en","centrist","private",2,"https://www.ynetnews.com/Integration/StoryRss3082.xml"),
 ("Arutz Sheva","IL","en","religious-nationalist","private",3,"https://www.israelnationalnews.com/Rss.aspx"),
 ("WAFA","PS","en","state-line (PA)","state",2,"https://english.wafa.ps/rss"),
 ("Palestine Chronicle","PS","en","pro-Palestinian","nonprofit",3,"https://www.palestinechronicle.com/feed/"),
 ("IRNA","IR","en","state-line","state",1,"https://en.irna.ir/rss"),
 ("Press TV","IR","en","state-line","state",1,"https://www.presstv.ir/rss"),
 ("Tehran Times","IR","en","state-aligned","private",2,"https://www.tehrantimes.com/rss"),
 ("Iran International","IR","en","opposition","private",2,"https://www.iranintl.com/feed"),
 ("Rudaw","IQ","en","Kurdish (KDP-aligned)","private",2,"https://www.rudaw.net/english/rss"),
 ("Iraqi News","IQ","en","centrist","private",3,"https://www.iraqinews.com/feed/"),
 ("Kurdistan24","IQ","en","Kurdish (KDP-aligned)","private",3,"https://www.kurdistan24.net/en/rss"),
 ("SANA","SY","en","state-line","state",2,"https://sana.sy/en/?feed=rss2"),
 ("Enab Baladi","SY","en","opposition/independent","nonprofit",2,"https://english.enabbaladi.net/feed/"),
 ("L'Orient Today","LB","en","centrist","private",2,"https://today.lorientlejour.com/rss"),
 ("Naharnet","LB","en","centrist","private",3,"https://www.naharnet.com/tags/lebanon/en/feed.atom"),
 ("Al-Manar (Hezbollah)","LB","en","party-line (Hezbollah)","party",3,"https://english.almanar.com.lb/rss"),
 ("The Jordan Times","JO","en","pro-government","private",2,"https://jordantimes.com/rss.xml"),
 ("Ahram Online","EG","en","state-line","state",1,"https://english.ahram.org.eg/rss"),
 ("Egypt Independent","EG","en","centrist","private",3,"https://egyptindependent.com/feed/"),
 ("Mada Masr","EG","en","independent/left-liberal","private",3,"https://www.madamasr.com/feed/"),
 ("Yemen Online","YE","en","centrist","private",3,"https://yemenonline.info/feed"),
 ("Saba (Sanaa)","YE","en","state-line (Houthi)","state",3,"https://www.saba.ye/en/rss"),
 # ---------------- East Asia ----------------
 ("Xinhua","CN","en","state-line","state",1,"http://www.xinhuanet.com/english/rss/worldrss.xml"),
 ("Global Times","CN","en","state-line/nationalist","state",1,"https://www.globaltimes.cn/rss/outbrain.xml"),
 ("CGTN","CN","en","state-line","state",1,"https://www.cgtn.com/subscribe/rss/section/world.xml"),
 ("China Daily","CN","en","state-line","state",1,"https://www.chinadaily.com.cn/rss/world-rss.xml"),
 ("People's Daily","CN","en","party-line (CCP)","party",1,"http://en.people.cn/rss/World.xml"),
 ("South China Morning Post","HK","en","centrist (Alibaba-owned)","private",1,"https://www.scmp.com/rss/91/feed"),
 ("Hong Kong Free Press","HK","en","liberal/independent","nonprofit",2,"https://hongkongfp.com/feed/"),
 ("RTHK","HK","en","public-service","public-service",2,"https://rthk.hk/rthk/news/rss/e_expressnews_elocal.xml"),
 ("Macau Business","MO","en","business","private",3,"https://www.macaubusiness.com/feed/"),
 ("Focus Taiwan (CNA)","TW","en","state-funded","state",1,"https://focustaiwan.tw/rss/news"),
 ("Taipei Times","TW","en","pro-independence (green)","private",2,"https://www.taipeitimes.com/xml/index.rss"),
 ("Taiwan News","TW","en","centrist","private",3,"https://www.taiwannews.com.tw/rss"),
 ("NHK","JP","ja","centrist","public-service",1,"https://www3.nhk.or.jp/rss/news/cat0.xml"),
 ("Kyodo News","JP","en","centrist","cooperative",1,"https://english.kyodonews.net/rss/news.xml"),
 ("The Japan Times","JP","en","liberal","private",1,"https://www.japantimes.co.jp/feed/"),
 ("Asahi Shimbun (AJW)","JP","en","liberal","private",2,"https://www.asahi.com/ajw/rss/ajw.rdf"),
 ("The Japan News (Yomiuri)","JP","en","conservative","private",2,"https://japannews.yomiuri.co.jp/feed/"),
 ("Nikkei Asia","JP","en","business/centre-right","private",1,"https://asia.nikkei.com/rss/feed/nar"),
 ("Yonhap News","KR","en","state-funded","state",1,"https://en.yna.co.kr/RSS/news.xml"),
 ("The Korea Herald","KR","en","centre-right","private",2,"https://www.koreaherald.com/rss/newsAll"),
 ("The Korea Times","KR","en","centrist","private",2,"https://www.koreatimes.co.kr/www/rss/rss.xml"),
 ("Hankyoreh","KR","en","progressive","private",2,"https://english.hani.co.kr/rss/"),
 ("Chosun Ilbo","KR","ko","conservative","private",2,"https://www.chosun.com/arc/outboundfeeds/rss/?outputType=xml"),
 ("KCNA Watch (North Korean state media mirror)","KP","en","state-line","state",2,"https://kcnawatch.org/feed/"),
 ("NK News","KP","en","independent (Seoul-based)","private",2,"https://www.nknews.org/feed/"),
 ("Montsame","MN","en","state-line","state",3,"https://montsame.mn/en/rss"),
 # ---------------- South Asia ----------------
 ("The Hindu","IN","en","centre-left","private",1,"https://www.thehindu.com/news/national/feeder/default.rss"),
 ("The Times of India","IN","en","centrist","private",1,"https://timesofindia.indiatimes.com/rssfeedstopstories.cms"),
 ("The Indian Express","IN","en","centre-left","private",1,"https://indianexpress.com/feed/"),
 ("Hindustan Times","IN","en","centrist","private",1,"https://www.hindustantimes.com/feeds/rss/india-news/rssfeed.xml"),
 ("NDTV","IN","en","liberal","private",2,"https://feeds.feedburner.com/ndtvnews-top-stories"),
 ("The Wire","IN","en","left-liberal","nonprofit",2,"https://thewire.in/rss"),
 ("Scroll.in","IN","en","left-liberal","private",3,"https://feeds.feedburner.com/ScrollinArticles.rss"),
 ("Swarajya","IN","en","right/Hindu-nationalist","private",3,"https://swarajyamag.com/feed"),
 ("OpIndia","IN","en","right/Hindu-nationalist","private",3,"https://www.opindia.com/feed/"),
 ("DD News","IN","en","state-line","state",2,"https://ddnews.gov.in/en/feed/"),
 ("Dawn","PK","en","liberal","private",1,"https://www.dawn.com/feeds/home"),
 ("The Express Tribune","PK","en","centrist","private",2,"https://tribune.com.pk/feed/home"),
 ("Geo News","PK","en","centrist","private",2,"https://www.geo.tv/rss/1/1"),
 ("Associated Press of Pakistan","PK","en","state-line","state",2,"https://www.app.com.pk/feed/"),
 ("The Daily Star","BD","en","centrist/liberal","private",1,"https://www.thedailystar.net/frontpage/rss.xml"),
 ("Dhaka Tribune","BD","en","centrist","private",2,"https://www.dhakatribune.com/feed/"),
 ("BSS","BD","en","state-line","state",2,"https://www.bssnews.net/rss/all"),
 ("Daily Mirror (Sri Lanka)","LK","en","centrist","private",2,"https://www.dailymirror.lk/RSS_Feeds/breaking-news"),
 ("Ada Derana","LK","en","centrist","private",2,"http://www.adaderana.lk/rss.php"),
 ("The Kathmandu Post","NP","en","liberal","private",2,"https://kathmandupost.com/rss"),
 ("Republica","NP","en","centrist","private",3,"https://myrepublica.nagariknetwork.com/feeds"),
 ("Kuensel","BT","en","state-aligned","private",3,"https://kuenselonline.com/feed/"),
 ("Sun.mv","MV","en","centrist","private",3,"https://en.sun.mv/feed"),
 ("TOLOnews","AF","en","independent","private",2,"https://tolonews.com/rss.xml"),
 ("Pajhwok Afghan News","AF","en","independent","private",3,"https://pajhwok.com/feed/"),
 ("Ariana News","AF","en","independent","private",3,"https://www.ariananews.af/feed/"),
 # ---------------- Central Asia ----------------
 ("The Astana Times","KZ","en","state-aligned","private",2,"https://astanatimes.com/feed/"),
 ("Kazinform","KZ","en","state-line","state",2,"https://www.inform.kz/en/rss"),
 ("Tengrinews","KZ","en","centrist","private",3,"https://tengrinews.kz/en/news/rss/"),
 ("Gazeta.uz","UZ","en","centrist","private",2,"https://www.gazeta.uz/en/rss/"),
 ("Kun.uz","UZ","en","centrist","private",3,"https://kun.uz/news/rss?lang=uz"),
 ("24.kg","KG","en","centrist","private",2,"https://24.kg/rss/"),
 ("AKIpress","KG","en","centrist","private",3,"https://akipress.com/rss/news.rss"),
 ("Asia-Plus","TJ","en","independent","private",3,"https://asiaplustj.info/en/rss"),
 ("Chronicles of Turkmenistan","TM","en","opposition (exiled)","nonprofit",3,"https://en.hronikatm.com/feed/"),
 ("Turkmenportal","TM","en","state-aligned","private",3,"https://turkmenportal.com/en/rss"),
 # ---------------- Southeast Asia ----------------
 ("The Straits Times","SG","en","state-aligned","private",1,"https://www.straitstimes.com/news/singapore/rss.xml"),
 ("CNA (Channel NewsAsia)","SG","en","state-owned/centrist","state",1,"https://www.channelnewsasia.com/api/v1/rss-outbound-feed?_format=xml"),
 ("The Star (Malaysia)","MY","en","centrist (MCA-linked)","private",2,"https://www.thestar.com.my/rss/News"),
 ("Malaysiakini","MY","en","liberal/independent","private",2,"https://www.malaysiakini.com/rss/en/news.rss"),
 ("Free Malaysia Today","MY","en","centrist","private",2,"https://www.freemalaysiatoday.com/feed/"),
 ("Bernama","MY","en","state-line","state",2,"https://www.bernama.com/en/rss"),
 ("The Jakarta Post","ID","en","liberal","private",1,"https://www.thejakartapost.com/feed"),
 ("Antara News","ID","en","state-line","state",2,"https://en.antaranews.com/rss/news.xml"),
 ("Tempo English","ID","en","liberal/independent","private",2,"https://rss.tempo.co/en"),
 ("Bangkok Post","TH","en","centrist","private",1,"https://www.bangkokpost.com/rss/data/topstories.xml"),
 ("The Nation Thailand","TH","en","centrist","private",2,"https://www.nationthailand.com/rss"),
 ("Thai PBS World","TH","en","centrist","public-service",2,"https://www.thaipbsworld.com/feed/"),
 ("Khaosod English","TH","en","liberal","private",3,"https://www.khaosodenglish.com/feed/"),
 ("VnExpress International","VN","en","state-controlled","state",1,"https://e.vnexpress.net/rss/news.rss"),
 ("VietnamPlus","VN","en","state-line","state",2,"https://en.vietnamplus.vn/rss/home.rss"),
 ("Vietnam News","VN","en","state-line","state",2,"https://vietnamnews.vn/rss/politics-laws.rss"),
 ("Philippine Daily Inquirer","PH","en","liberal","private",1,"https://www.inquirer.net/fullfeed"),
 ("Rappler","PH","en","liberal","private",2,"https://www.rappler.com/feed/"),
 ("Philstar","PH","en","centrist","private",2,"https://www.philstar.com/rss/headlines"),
 ("Philippine News Agency","PH","en","state-line","state",2,"https://www.pna.gov.ph/rss"),
 ("Manila Bulletin","PH","en","centre-right","private",2,"https://mb.com.ph/rss/news"),
 ("Khmer Times","KH","en","pro-government","private",2,"https://www.khmertimeskh.com/feed/"),
 ("The Phnom Penh Post","KH","en","centrist","private",3,"https://phnompenhpost.com/feed/"),
 ("The Laotian Times","LA","en","centrist","private",3,"https://laotiantimes.com/feed/"),
 ("The Irrawaddy","MM","en","opposition/independent","nonprofit",2,"https://www.irrawaddy.com/feed"),
 ("Myanmar Now","MM","en","opposition/independent","nonprofit",3,"https://myanmar-now.org/en/feed/"),
 ("Global New Light of Myanmar","MM","en","state-line (junta)","state",3,"https://www.gnlm.com.mm/feed/"),
 ("Borneo Bulletin","BN","en","pro-government","private",3,"https://borneobulletin.com.bn/feed/"),
 ("Tatoli","TL","en","state-line","state",3,"https://en.tatoli.tl/feed/"),
 # ---------------- Oceania ----------------
 ("ABC News (Australia)","AU","en","centrist","public-service",1,"https://www.abc.net.au/news/feed/2942460/rss.xml"),
 ("The Sydney Morning Herald","AU","en","centre-left","private",1,"https://www.smh.com.au/rss/feed.xml"),
 ("The Age","AU","en","centre-left","private",2,"https://www.theage.com.au/rss/feed.xml"),
 ("The Australian","AU","en","conservative","private",2,"https://www.theaustralian.com.au/feed/"),
 ("Sky News Australia","AU","en","conservative","private",2,"https://www.skynews.com.au/feed"),
 ("Guardian Australia","AU","en","centre-left","private",2,"https://www.theguardian.com/australia-news/rss"),
 ("RNZ","NZ","en","centrist","public-service",1,"https://www.rnz.co.nz/rss/national.xml"),
 ("RNZ Pacific","NZ","en","centrist","public-service",1,"https://www.rnz.co.nz/rss/pacific.xml"),
 ("NZ Herald","NZ","en","centre-right","private",2,"https://www.nzherald.co.nz/arc/outboundfeeds/rss/section/nz/?outputType=xml"),
 ("Stuff","NZ","en","centre-left","private",2,"https://www.stuff.co.nz/rss"),
 ("The Fiji Times","FJ","en","centrist","private",2,"https://www.fijitimes.com.fj/feed/"),
 ("Fiji Sun","FJ","en","pro-government","private",3,"https://fijisun.com.fj/feed/"),
 ("Post-Courier","PG","en","centrist","private",2,"https://www.postcourier.com.pg/feed/"),
 ("The National (PNG)","PG","en","centrist","private",3,"https://www.thenational.com.pg/feed/"),
 ("Samoa Observer","WS","en","independent","private",3,"https://www.samoaobserver.ws/rss"),
 ("Matangi Tonga","TO","en","independent","private",3,"https://matangitonga.to/rss.xml"),
 ("SIBC","SB","en","public-service","public-service",3,"https://www.sibc.com.sb/feed/"),
 ("Solomon Star","SB","en","centrist","private",3,"https://www.solomonstarnews.com/feed/"),
 ("Vanuatu Daily Post","VU","en","independent","private",3,"https://www.dailypost.vu/search/?f=rss"),
 ("Island Times (Palau)","PW","en","independent","private",3,"https://islandtimes.org/feed/"),
 ("Marshall Islands Journal","MH","en","independent","private",3,"https://marshallislandsjournal.com/feed/"),
 ("Kaselehlie Press","FM","en","independent","private",3,"https://www.kpress.info/index.php/feed"),
 ("Kiribati Independent","KI","en","independent","private",3,"https://www.kiribatiindependent.com/feed"),
 ("Tuvalu Broadcasting","TV","en","public-service","public-service",3,"https://www.tuvalu.tv/feed"),
 ("Nauru Government","NR","en","state-line","state",3,"https://nauru.gov.nr/rss"),
 # ---------------- Africa ----------------
 ("Punch","NG","en","centrist","private",1,"https://punchng.com/feed/"),
 ("Vanguard","NG","en","centrist","private",2,"https://www.vanguardngr.com/feed/"),
 ("Premium Times","NG","en","liberal/independent","private",2,"https://www.premiumtimesng.com/feed"),
 ("Channels TV","NG","en","centrist","private",2,"https://www.channelstv.com/feed/"),
 ("News Agency of Nigeria","NG","en","state-line","state",2,"https://nannews.ng/feed/"),
 ("Daily Nation","KE","en","centrist","private",1,"https://nation.africa/kenya/rss.xml"),
 ("The Standard (Kenya)","KE","en","centrist","private",2,"https://www.standardmedia.co.ke/rss/headlines.php"),
 ("Capital FM","KE","en","centrist","private",3,"https://www.capitalfm.co.ke/news/feed/"),
 ("KBC","KE","en","state-line","state",2,"https://www.kbc.co.ke/feed/"),
 ("News24","ZA","en","centrist","private",1,"https://feeds.24.com/articles/news24/TopStories/rss"),
 ("Daily Maverick","ZA","en","liberal/independent","private",1,"https://www.dailymaverick.co.za/rss"),
 ("Mail & Guardian","ZA","en","left-liberal","private",2,"https://mg.co.za/atom/"),
 ("SABC News","ZA","en","public-service","public-service",2,"https://www.sabcnews.com/sabcnews/feed/"),
 ("IOL","ZA","en","centrist (Sekunjalo-owned)","private",2,"https://www.iol.co.za/rss"),
 ("GhanaWeb","GH","en","centrist","private",2,"https://www.ghanaweb.com/GhanaHomePage/rss/news.xml"),
 ("MyJoyOnline","GH","en","centrist","private",2,"https://www.myjoyonline.com/feed/"),
 ("Ghana News Agency","GH","en","state-line","state",3,"https://gna.org.gh/feed/"),
 ("Addis Standard","ET","en","independent","private",2,"https://addisstandard.com/feed/"),
 ("Ethiopian News Agency","ET","en","state-line","state",2,"https://www.ena.et/en/rss"),
 ("Fana Broadcasting","ET","en","pro-government","private",3,"https://www.fanabc.com/english/feed/"),
 ("Morocco World News","MA","en","pro-government","private",2,"https://www.moroccoworldnews.com/feed"),
 ("Hespress English","MA","en","centrist","private",2,"https://en.hespress.com/feed"),
 ("MAP","MA","en","state-line","state",2,"https://www.mapnews.ma/en/rss"),
 ("Algérie Presse Service","DZ","en","state-line","state",2,"https://www.aps.dz/en/?format=feed&type=rss"),
 ("TSA Algérie","DZ","fr","independent","private",3,"https://www.tsa-algerie.com/feed/"),
 ("TAP","TN","en","state-line","state",2,"https://www.tap.info.tn/en/rss"),
 ("Tunisie Numérique","TN","fr","centrist","private",3,"https://www.tunisienumerique.com/feed.xml"),
 ("The Libya Observer","LY","en","pro-Tripoli","private",2,"https://libyaobserver.ly/rss.xml"),
 ("Libya Herald","LY","en","centrist","private",3,"https://libyaherald.com/feed/"),
 ("Sudan Tribune","SD","en","independent","private",1,"https://sudantribune.com/feed/"),
 ("Radio Dabanga","SD","en","independent","nonprofit",2,"https://www.dabangasudan.org/en/all-news/feed"),
 ("Eye Radio","SS","en","independent","nonprofit",2,"https://www.eyeradio.org/feed/"),
 ("Radio Tamazuj","SS","en","independent","nonprofit",3,"https://www.radiotamazuj.org/en/rss"),
 ("Hiiraan Online","SO","en","independent","private",2,"https://www.hiiraan.com/rss.xml"),
 ("Garowe Online","SO","en","independent (Puntland)","private",3,"https://www.garoweonline.com/en/rss"),
 ("SONNA","SO","en","state-line","state",3,"https://sonna.so/en/feed/"),
 ("Shabait","ER","en","state-line","state",3,"https://shabait.com/feed/"),
 ("La Nation (Djibouti)","DJ","fr","state-line","state",3,"https://www.lanation.dj/feed/"),
 ("Daily Monitor","UG","en","independent","private",2,"https://www.monitor.co.ug/rss.xml"),
 ("New Vision","UG","en","state-aligned","state",2,"https://www.newvision.co.ug/rss"),
 ("Nile Post","UG","en","centrist","private",3,"https://nilepost.co.ug/feed"),
 ("The Citizen (Tanzania)","TZ","en","centrist","private",2,"https://www.thecitizen.co.tz/rss.xml"),
 ("Daily News (Tanzania)","TZ","en","state-line","state",3,"https://dailynews.co.tz/feed/"),
 ("The New Times","RW","en","pro-government","private",2,"https://www.newtimes.co.rw/rss"),
 ("KT Press","RW","en","pro-government","private",3,"https://www.ktpress.rw/feed/"),
 ("Iwacu","BI","fr","independent","private",3,"https://www.iwacu-burundi.org/feed/"),
 ("Actualite.cd","CD","fr","independent","private",2,"https://actualite.cd/feed"),
 ("Radio Okapi (UN)","CD","fr","institutional","state",2,"https://www.radiookapi.net/rss.xml"),
 ("7sur7.cd","CD","fr","centrist","private",3,"https://7sur7.cd/feed"),
 ("Les Dépêches de Brazzaville","CG","fr","pro-government","private",3,"https://www.adiac-congo.com/rss.xml"),
 ("Journal du Cameroun","CM","en","centrist","private",3,"https://fr.journalducameroun.com/feed/"),
 ("Cameroon News Agency","CM","en","independent","private",3,"https://cameroonnewsagency.com/feed/"),
 ("Gabonreview","GA","fr","independent","private",3,"https://www.gabonreview.com/feed/"),
 ("Ahora EG","GQ","es","independent","private",3,"https://ahoraeg.com/feed/"),
 ("Corbeau News Centrafrique","CF","fr","independent","private",3,"https://corbeaunews-centrafrique.org/feed/"),
 ("Alwihda Info","TD","fr","independent","private",3,"https://www.alwihdainfo.com/rss/"),
 ("Tchadinfos","TD","fr","centrist","private",3,"https://tchadinfos.com/feed/"),
 ("ActuNiger","NE","fr","independent","private",3,"https://www.actuniger.com/feed"),
 ("Maliweb","ML","fr","independent","private",3,"https://www.maliweb.net/feed"),
 ("Journal du Mali","ML","fr","centrist","private",3,"https://www.journaldumali.com/feed/"),
 ("Lefaso.net","BF","fr","independent","private",3,"https://lefaso.net/spip.php?page=backend"),
 ("AIB Burkina","BF","fr","state-line","state",3,"https://www.aib.media/feed/"),
 ("Seneweb","SN","fr","centrist","private",2,"https://www.seneweb.com/feed"),
 ("Agence de Presse Sénégalaise","SN","fr","state-line","state",3,"https://aps.sn/feed/"),
 ("The Point (Gambia)","GM","en","independent","private",3,"https://thepoint.gm/posts/rss/xml"),
 ("The Standard (Gambia)","GM","en","independent","private",3,"https://standard.gm/feed/"),
 ("Guinéenews","GN","fr","independent","private",3,"https://guineenews.org/feed/"),
 ("O Democrata","GW","pt","independent","private",3,"https://www.odemocratagb.com/?feed=rss2"),
 ("Awoko","SL","en","independent","private",3,"https://awoko.org/feed/"),
 ("Sierra Leone Telegraph","SL","en","independent","private",3,"https://www.thesierraleonetelegraph.com/feed/"),
 ("FrontPage Africa","LR","en","independent","private",2,"https://frontpageafricaonline.com/feed/"),
 ("Abidjan.net","CI","fr","centrist","private",2,"https://news.abidjan.net/rss"),
 ("Fraternité Matin","CI","fr","state-line","state",3,"https://www.fratmat.info/rss"),
 ("Republic of Togo","TG","fr","state-line","state",3,"https://www.republicoftogo.com/rss"),
 ("Togo First","TG","en","business","private",3,"https://www.togofirst.com/en/?format=feed"),
 ("24h au Bénin","BJ","fr","centrist","private",3,"https://www.24haubenin.info/spip.php?page=backend"),
 ("La Nation Bénin","BJ","fr","state-line","state",3,"https://lanation.bj/feed"),
 ("Sahara Medias","MR","fr","independent","private",3,"https://www.saharamedias.net/feed/"),
 ("Expresso das Ilhas","CV","pt","centrist","private",3,"https://expressodasilhas.cv/rss"),
 ("Téla Nón","ST","pt","independent","private",3,"https://www.telanon.info/feed/"),
 ("Angop","AO","pt","state-line","state",2,"https://www.angop.ao/feed/"),
 ("Novo Jornal","AO","pt","independent","private",3,"https://www.novojornal.co.ao/rss"),
 ("Club of Mozambique","MZ","en","business","private",2,"https://clubofmozambique.com/feed/"),
 ("Lusaka Times","ZM","en","independent","private",2,"https://www.lusakatimes.com/feed/"),
 ("Zambia Daily Mail","ZM","en","state-line","state",3,"https://www.daily-mail.co.zm/feed/"),
 ("News Diggers","ZM","en","independent","private",3,"https://diggers.news/feed/"),
 ("The Herald (Zimbabwe)","ZW","en","state-line","state",2,"https://www.herald.co.zw/feed/"),
 ("NewsDay Zimbabwe","ZW","en","independent","private",2,"https://www.newsday.co.zw/feed"),
 ("New Zimbabwe","ZW","en","independent","private",3,"https://www.newzimbabwe.com/feed/"),
 ("Nyasa Times","MW","en","independent","private",2,"https://www.nyasatimes.com/feed/"),
 ("Malawi24","MW","en","independent","private",3,"https://malawi24.com/feed/"),
 ("Mmegi","BW","en","independent","private",2,"https://www.mmegi.bw/rss"),
 ("Sunday Standard","BW","en","independent","private",3,"https://www.sundaystandard.info/feed/"),
 ("The Namibian","NA","en","independent","private",2,"https://www.namibian.com.na/feed/"),
 ("New Era","NA","en","state-line","state",3,"https://neweralive.na/feed"),
 ("Lesotho Times","LS","en","independent","private",3,"https://lestimes.com/?feed=rss2"),
 ("Eswatini Observer","SZ","en","royal-aligned","private",3,"https://new.observer.org.sz/feed"),
 ("L'Express de Madagascar","MG","fr","centrist","private",3,"https://www.lexpress.mg/feeds/posts/default"),
 ("Midi Madagasikara","MG","fr","centrist","private",3,"https://www.midi-madagasikara.mg/feed/"),
 ("Le Mauricien","MU","fr","independent","private",3,"https://www.lemauricien.com/feed/"),
 ("Defimedia","MU","fr","centrist","private",3,"https://defimedia.info/rss.xml"),
 ("Seychelles News Agency","SC","en","state-line","state",3,"http://www.seychellesnewsagency.com/rss"),
 ("Al-Watwan","KM","fr","state-line","state",3,"https://alwatwan.net/feed"),
 # ---------------- Canada / Mexico / Central America / Caribbean ----------------
 ("CBC News","CA","en","centrist","public-service",1,"https://www.cbc.ca/webfeed/rss/rss-topstories"),
 ("The Globe and Mail","CA","en","centre-right","private",1,"https://www.theglobeandmail.com/arc/outboundfeeds/rss/category/world/"),
 ("National Post","CA","en","conservative","private",2,"https://nationalpost.com/feed"),
 ("Toronto Star","CA","en","liberal","private",2,"https://www.thestar.com/search/?f=rss&t=article&l=25&s=start_time&sd=desc"),
 ("CTV News","CA","en","centrist","private",2,"https://www.ctvnews.ca/arc/outboundfeeds/rss/?outputType=xml"),
 ("Le Devoir","CA","fr","left/Quebec-nationalist","private",2,"https://www.ledevoir.com/rss/manchettes.xml"),
 ("Rebel News","CA","en","populist-right","private",3,"https://www.rebelnews.com/rss"),
 ("El Universal","MX","es","centrist","private",1,"https://www.eluniversal.com.mx/arc/outboundfeeds/rss/?outputType=xml"),
 ("La Jornada","MX","es","left","private",2,"https://www.jornada.com.mx/rss/edicion.xml?v=1"),
 ("Milenio","MX","es","centrist","private",2,"https://www.milenio.com/rss"),
 ("Proceso","MX","es","left-liberal","private",3,"https://www.proceso.com.mx/feeds/rss"),
 ("Mexico News Daily","MX","en","centrist","private",2,"https://mexiconewsdaily.com/feed/"),
 ("Prensa Libre","GT","es","centre-right","private",2,"https://www.prensalibre.com/feed/"),
 ("La Prensa (Honduras)","HN","es","centre-right","private",2,"https://www.laprensa.hn/rss"),
 ("El Heraldo (Honduras)","HN","es","centre-right","private",3,"https://www.elheraldo.hn/rss"),
 ("El Faro","SV","es","independent/investigative","nonprofit",2,"https://elfaro.net/en/feed"),
 ("La Prensa Gráfica","SV","es","centre-right","private",2,"https://www.laprensagrafica.com/rss"),
 ("Confidencial","NI","es","opposition/independent","private",2,"https://confidencial.digital/feed/"),
 ("El 19 Digital","NI","es","state-line (FSLN)","state",3,"https://www.el19digital.com/rss"),
 ("La Nación (Costa Rica)","CR","es","centre-right","private",2,"https://www.nacion.com/rss"),
 ("The Tico Times","CR","en","centrist","private",3,"https://ticotimes.net/feed"),
 ("La Prensa (Panamá)","PA","es","centrist","private",2,"https://www.prensa.com/arc/outboundfeeds/rss/?outputType=xml"),
 ("Granma","CU","en","party-line (PCC)","party",2,"https://en.granma.cu/feed"),
 ("Cubadebate","CU","es","state-line","state",2,"http://www.cubadebate.cu/feed/"),
 ("14ymedio","CU","es","opposition/independent","private",2,"https://www.14ymedio.com/rss"),
 ("CiberCuba","CU","es","opposition (exiled)","private",3,"https://www.cibercuba.com/rss.xml"),
 ("Le Nouvelliste","HT","fr","centrist","private",2,"https://lenouvelliste.com/rss"),
 ("Haïti Libre","HT","fr","centrist","private",3,"https://www.haitilibre.com/rss-flash.php"),
 ("Diario Libre","DO","es","centrist","private",2,"https://www.diariolibre.com/rss/portada.xml"),
 ("Dominican Today","DO","en","centrist","private",3,"https://dominicantoday.com/feed/"),
 ("Jamaica Gleaner","JM","en","centrist","private",2,"https://jamaica-gleaner.com/feed"),
 ("Jamaica Observer","JM","en","centrist","private",2,"https://www.jamaicaobserver.com/feed/"),
 ("Trinidad Express","TT","en","centrist","private",2,"https://trinidadexpress.com/search/?f=rss"),
 ("Nation News (Barbados)","BB","en","centrist","private",3,"https://www.nationnews.com/feed/"),
 ("Barbados Today","BB","en","centrist","private",3,"https://barbadostoday.bb/feed/"),
 ("The Tribune (Bahamas)","BS","en","centrist","private",3,"https://www.tribune242.com/rss/headlines/"),
 ("The Nassau Guardian","BS","en","centrist","private",3,"https://www.thenassauguardian.com/feed/"),
 ("Breaking Belize News","BZ","en","independent","private",3,"https://www.breakingbelizenews.com/feed/"),
 ("Amandala","BZ","en","independent","private",3,"https://amandala.com.bz/news/feed/"),
 ("Stabroek News","GY","en","independent","private",2,"https://www.stabroeknews.com/feed/"),
 ("Kaieteur News","GY","en","opposition-leaning","private",3,"https://www.kaieteurnewsonline.com/feed/"),
 ("Starnieuws","SR","nl","centrist","private",3,"https://www.starnieuws.com/rss"),
 ("Antigua Observer","AG","en","independent","private",3,"https://antiguaobserver.com/feed/"),
 ("WINN FM","KN","en","independent","private",3,"https://www.winnmediaskn.com/feed/"),
 ("Dominica News Online","DM","en","independent","private",3,"https://dominicanewsonline.com/news/feed/"),
 ("St. Lucia Times","LC","en","independent","private",3,"https://stluciatimes.com/feed/"),
 ("iWitness News","VC","en","independent","private",3,"https://www.iwnsvg.com/feed/"),
 ("NOW Grenada","GD","en","independent","private",3,"https://nowgrenada.com/feed/"),
 # ---------------- South America ----------------
 ("Folha de S.Paulo","BR","pt","centrist","private",1,"https://feeds.folha.uol.com.br/mundo/rss091.xml"),
 ("Agência Brasil","BR","pt","state-line","state",2,"https://agenciabrasil.ebc.com.br/rss/ultimasnoticias/feed.xml"),
 ("Brasil de Fato","BR","pt","left","nonprofit",3,"https://www.brasildefato.com.br/feed"),
 ("Gazeta do Povo","BR","pt","conservative","private",3,"https://www.gazetadopovo.com.br/feed/rss/"),
 ("The Brazilian Report","BR","en","centrist","private",2,"https://brazilian.report/feed/"),
 ("Estadão","BR","pt","centre-right","private",2,"https://www.estadao.com.br/arc/outboundfeeds/feeds/rss/sections/geral/?body=%7B%22layout%22:%22google-news%22%7D"),
 ("El Tiempo","CO","es","centre-right","private",1,"https://www.eltiempo.com/rss/colombia.xml"),
 ("El Espectador","CO","es","centre-left","private",2,"https://www.elespectador.com/arc/outboundfeeds/rss/"),
 ("Colombia Reports","CO","en","independent","private",3,"https://colombiareports.com/feed/"),
 ("TeleSUR English","VE","en","state-line/left","state",1,"https://www.telesurenglish.net/feed/"),
 ("El Nacional","VE","es","opposition","private",2,"https://www.elnacional.com/feed/"),
 ("Efecto Cocuyo","VE","es","independent","nonprofit",3,"https://efectococuyo.com/feed/"),
 ("Últimas Noticias","VE","es","pro-government","private",3,"https://ultimasnoticias.com.ve/feed/"),
 ("El Universo","EC","es","centre-right","private",2,"https://www.eluniverso.com/arc/outboundfeeds/rss/?outputType=xml"),
 ("Primicias","EC","es","centrist","private",3,"https://www.primicias.ec/rss/latest"),
 ("El Comercio (Perú)","PE","es","centre-right","private",2,"https://elcomercio.pe/arc/outboundfeeds/rss/category/politica/?outputType=xml"),
 ("La República (Perú)","PE","es","centre-left","private",2,"https://larepublica.pe/rss.xml"),
 ("RPP","PE","es","centrist","private",2,"https://rpp.pe/feed"),
 ("Andina","PE","es","state-line","state",3,"https://andina.pe/agencia/rss"),
 ("La Razón (Bolivia)","BO","es","centrist","private",2,"https://www.la-razon.com/feed/"),
 ("El Deber","BO","es","centre-right","private",2,"https://eldeber.com.bo/feed"),
 ("ABI","BO","es","state-line","state",3,"https://abi.bo/rss"),
 ("La Tercera","CL","es","centre-right","private",2,"https://www.latercera.com/rss"),
 ("El Mostrador","CL","es","centre-left","private",2,"https://www.elmostrador.cl/feed/"),
 ("BioBioChile","CL","es","centrist","private",2,"https://feeds.feedburner.com/radiobiobio/NNeJ"),
 ("Clarín","AR","es","centre-right","private",1,"https://www.clarin.com/rss/lo-ultimo/"),
 ("Página/12","AR","es","left","private",2,"https://www.pagina12.com.ar/arc/outboundfeeds/rss/?outputType=xml"),
 ("Infobae","AR","es","centrist","private",1,"https://www.infobae.com/arc/outboundfeeds/rss/category/america/mundo/"),
 ("Ámbito","AR","es","business","private",3,"https://www.ambito.com/rss/ultimas-noticias.xml"),
 ("Buenos Aires Times","AR","en","centrist","private",2,"https://www.batimes.com.ar/feed"),
 ("El País (Uruguay)","UY","es","centre-right","private",2,"https://www.elpais.com.uy/rss"),
 ("la diaria","UY","es","left","cooperative",3,"https://ladiaria.com.uy/feeds/articulos/"),
 ("ABC Color","PY","es","centre-right","private",2,"https://www.abc.com.py/arc/outboundfeeds/rss/?outputType=xml"),
 ("Última Hora","PY","es","centrist","private",3,"https://www.ultimahora.com/rss"),
]

# Coarse polarity used to detect "two sides" when no better split (country) exists.
LEFT_MARKERS = ("left", "socialist", "communist", "marxist", "progressive", "liberal", "green", "social-democratic", "pro-palestinian")
RIGHT_MARKERS = ("right", "conservative", "nationalist", "libertarian", "religious", "royal", "business", "free-market")
STATE_MARKERS = ("state", "party-line", "pro-government", "state-aligned", "state-funded", "state-controlled", "junta", "houthi", "hezbollah")

def polarity(leaning: str, ownership: str = "") -> str:
    l = (leaning or "").lower()
    if any(m in l for m in STATE_MARKERS) or ownership in ("state", "party"):
        return "state/government"
    if "centre-left" in l or "center-left" in l:
        return "left"
    if "centre-right" in l or "center-right" in l:
        return "right"
    if "centrist" in l or "centre" in l:
        return "centre"
    if any(m in l for m in LEFT_MARKERS):
        return "left"
    if any(m in l for m in RIGHT_MARKERS):
        return "right"
    if "independent" in l or "opposition" in l:
        return "independent/opposition"
    return "other"

def outlet_records():
    recs = []
    for i, (name, cc, lang, leaning, ownership, tier, url) in enumerate(OUTLETS):
        recs.append({
            "id": f"o{i}", "name": name, "country": cc, "lang": lang, "leaning": leaning,
            "ownership": ownership, "tier": tier, "feed": url, "kind": "direct",
            "polarity": polarity(leaning, ownership),
        })
    return recs

DIRECT_COUNTRIES = {o[1] for o in OUTLETS}
